api/v1alpha1/hazelcast_types.go, api/v1alpha1/managementcenter_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/crd/bases/hazelcast.com_managementcenters.yaml, config/samples/_v1alpha1_hazelcast.yaml, config/samples/_v1alpha1_hazelcast_expose_externally.yaml, config/samples/_v1alpha1_managementcenter.yaml, controllers/naming/constants.go, test/e2e/config/hazelcast/config.go
fixes #102
Other change:
- use static version for tests
=> Upgrade default versions of Hazelcast(5.0.2) and Management Center(5.0.4)

api/v1alpha1/hazelcast_types.go, controllers/hazelcast/hazelcast_resources.go
=> Fix annotation for expose externally member access

api/v1alpha1/managementcenter_types.go, bundle.yaml, config/crd/bases/hazelcast.com_managementcenters.yaml, controllers/managementcenter/managementcenter_resources.go, test/integration/hazelcast_controller_test.go, test/integration/managementcenter_controller_test.go, test/integration/util_test.go
Support pod scheduling for ManagementCenter
=> [CN-307] MC pod scheduling support

.github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-e2e-ocp.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/pull-request.yml
This PR allows us to run nightly tests on specific branches. Our main goal is to run tests on the release branch before we create the release.
=> Add image build step into nightly builds

README.md
Update README with Turbine support
=> [CN-315] Add Turbine support to feature list

.github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-e2e-ocp.yaml
Disable cleanup in nightlies if there is a failure
=> [CN-332] Do not delete the clusters if there is a failure

test/e2e/hazelcast_controller_e2e_test.go
Will propose new test in a separate PR.
=> [CN-334] Temporarily disable pod status assertion

Makefile
Increase the overall and the eventually block timeouts to fix problem in OCP and AKS
=> Increase the timeout to fix timeout problems in OCP and AKS

.github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-e2e-ocp.yaml
This PR reverts the two PR merged before for skipping the cluster deletion in case of a failure.
=> Revert skip deleting clusters

test/e2e/helpers_test.go, test/e2e/management_center_test.go, test/e2e/util_test.go
Increase timeout in 2 places that could causes the issue in test run
=> CN-356-Separate timeout values

test/e2e/e2e_suite_test.go
Make installation of cleanup Daemonset to run once on process 1
=> Fix DS installation to one process

api/v1alpha1/hazelcast_types.go, test/e2e/hazelcast_persistence_test.go, test/e2e/helpers_test.go
* Increase timeouts for specific cases
* Check nil pointer to prevent panic
* Make Hostpath and external backup and restore tests serial
=> Make change in E2E test

.github/actions/operator-tests/action.yml, .github/scripts/publish-rhel.sh, .github/workflows/certification-tests-and-release.yaml, .github/workflows/publish-release.yaml
- Make PROJECT_IT without osp prefix
- Remove unnecessary functions
=> Fixed release workflow 

test/e2e/hazelcast_map_test.go
The check needs to be in eventually block since we are missing updated config for some test runs.
=> [CN-433] Wrap check into eventually block

api/v1alpha1/hazelcast_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, controllers/hazelcast/hazelcast_resources.go, internal/naming/constants.go
Related to https://github.com/hazelcast/platform-operator-agent/pull/15
=> [CN-350] Pass only secret name for restore agent credentials

controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_status.go
HotBackup with BucketURI could trigger backup upload for Local backupType which is not expected as there wont be sidecar upload agent present.
=> [CN-437] Fix for HotBackup with BucketURI always triggering backup upload

.github/newrelic/newrelic-values.yaml
In order to reduce the amount of ingest data enabled the `lowDataMode`
=> Enable New Relic low data mode

.github/workflows/docs-release.yaml, .github/workflows/nightly-e2e-gke.yaml
=> Rename workflow and job name

.github/workflows/generate-test-report.yaml, test/e2e/custom_resource_test.go
* Added CR_ID of the test to the top of the report
* Cleanup/beautified the report body (removed time, "by step" lines, trace info for each step)
* Increased number of history from 30 to 100
* Added link to new relic
=> Added CR_ID for the each test 

controllers/hazelcast/hazelcast_resources.go
Test:
```sh
$ k rollout restart statefulset hazelcast
```
Result:
```sh
$ k get pod -w
hazelcast-2   1/1     Terminating         0          8m4s
hazelcast-2   0/1     Terminating         0          8m5s
hazelcast-2   0/1     Terminating         0          8m10s
hazelcast-2   0/1     Terminating         0          8m10s
hazelcast-2   0/1     Pending             0          0s
hazelcast-2   0/1     Pending             0          0s
hazelcast-2   0/1     ContainerCreating   0          0s
hazelcast-2   0/1     Running             0          2s
hazelcast-2   1/1     Running             0          10s
hazelcast-1   1/1     Terminating         0          9m10s
hazelcast-1   0/1     Terminating         0          9m11s
hazelcast-1   0/1     Terminating         0          9m20s
hazelcast-1   0/1 …
```
=> [CN-402] Fix Hazelcast statefulset rollout restart

internal/backup/backup.go
Changed steps count and factor. In total it should take the same amount of time.
=> [CN-474] Change hotBackup retry count from 4 to 8

.github/workflows/generate-test-report.yaml
* Added custom defect classification based on test suites (backup slow, expose externally, map custom class, map persistence, map, persistence, hazelcast test, wan test, management center, phone home)
* Fixed unknown duration in the report
* Added ERROR_LINE link that point directly to the code line in GitHub repository
* Marked all steps as passed and the last step as failed
* Added environment variables that point to all existing reports, which simplifies the navigation
=> Improved display of test report

.github/workflows/backup-e2e-gke.yaml, .github/workflows/certification-tests-and-release.yaml, .github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/publish-release.yaml
* The secrets in workflow_call becomes inheritable from the master job
* Added create cluster dependency for report creation step
=> Cleaned up and improved the existing workflows

.github/workflows/generate-test-report.yaml, .github/workflows/nightly-e2e-kind.yaml, README.md, test/e2e/helpers_test.go
* Added kind workflow to run the test nightly
* Added status badges to all nightly tests
=> Added nightly tests workflow running on a kind

.github/workflows/generate-test-report.yaml
Replaced the action to fix the issue with publishing the report at the same time
=> Replace github action required for publishing pages/test report

controllers/hazelcast/hazelcast_resources.go
=>  [CN-614] [5.5] Add additional port to the LB discovery service

README.md, config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
Add new feature to README.md, hazelcast-platform-operator.clusterserviceversion.yaml file and add new tutorial links to the documentation
=> Add new feature description to README.md and hazelcast-platform-operator.clusterserviceversion.yaml file

test/integration/hazelcast_controller_test.go
=> [CN-616] Fix flaky HotBackup with labels test

controllers/hazelcast/hazelcast_resources.go, internal/util/util.go
Similar to change in helm charts: https://github.com/hazelcast/charts/pull/306
We also change our service to headless so istio know how to route traffic.
Closes #385.
=> Add appProtocol and use headless service for Istio compatibility (#385)

.github/workflows/backup-e2e-gke.yaml, .github/workflows/generate-test-report.yaml, .github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-e2e-kind.yaml, .github/workflows/nightly-e2e-ocp.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml
The test report became broken after we add retries run for a failed test. 
Now all reports will be visible as it was before. The test report will show only the last run.
=> ci: Update Allure report to support retries in test run

config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
Since the last change of capabilities parameter, we have added multiple features to provide full lifecycle management of Hazelcast clusters.
https://sdk.operatorframework.io/docs/overview/operator-capabilities/
At OCP OperatorHub dashboard, users will see that information.
=> Change capabilities at CSV from Seamless Upgrades to Full Lifecycle

api/v1alpha1/hazelcast_validation.go, api/v1alpha1/hazelcast_webhook.go, api/v1alpha1/map_validation.go, api/v1alpha1/map_webhook.go, api/v1alpha1/topic_validation.go, api/v1alpha1/topic_webhook.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/map_controller.go, internal/util/util.go, test/e2e/hazelcast_map_persistence_test.go, test/e2e/hazelcast_map_test.go
Add validating webhook for Hazlecast cluster and Topic data structure CRs. 
This change allows operator to report issues with CRs before they are applied.
=> [CN-602] Add existing CR validation to validating webhook

.github/workflows/backup-e2e-gke.yaml, .github/workflows/newrelic-gke.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/pull-request.yml, controllers/hazelcast/hazelcast_resources.go, test/e2e/hazelcast_expose_externally_test.go
Fix for first member trying to assume external IP of the discovery service load balancer.
=> [CN-614] Use ServicePerPodLabelName when ExposeExternally is set

.github/workflows/backup-e2e-gke.yaml, .github/workflows/create-release.yaml, .github/workflows/docs-release.yaml, .github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-e2e-kind.yaml, .github/workflows/nightly-e2e-ocp.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/publish-release.yaml, .github/workflows/publish-snapshot.yaml, .github/workflows/pull-request-label-update.yaml, .github/workflows/pull-request.yml, Makefile
Changes:
- Separated label adder job into a separate workflow. It is now triggered only at PR creation.
- Changed k8s test environment from GKE to Kind.
- Increased Ginkgo parallel process count to 4.
PR built time decreased at least 10 minutes.
=> [CN-627] Update pull request builder to use Kind cluster

PROJECT, api/v1alpha1/cache_webhook.go, api/v1alpha1/replicatedmap_webhook.go, bundle.yaml, config/webhook/manifests.yaml, main.go
=> Add empty webhook for replicatedmap and cache

config/webhook/manifests.yaml
Auto generator tools refactor the manifest file as below, it is better to keep it this way
=> Refactor webhook manifest

controllers/hazelcast/hazelcast_resources.go, test/integration/hazelcast_controller_test.go
refactoring path concatenations by using path#Join
=> [CN-662] path join refactoring

api/v1alpha1/hotbackup_types.go, controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_controller_test.go, test/e2e/hazelcast_persistence_test.go, test/e2e/hazelcast_test.go, test/e2e/helpers_test.go, test/e2e/options_test.go
Do not return error when Hazelcast CR is not ready yet.
=> [CN-643] Allow to create HotBackup before Hazelcast cluster is ready

.github/workflows/k8s-dist-tests.yaml
=> Remove concurrecy from dist tests

DEVELOPER.md, Makefile, internal/hazelcast-client/config.go, internal/hazelcast-client/config_test_unit.go
Remove localrun related tags and documentation from the codebase.
Localrun tag useage is not promoted anymore.
=> Remove localrun

test/e2e/hazelcast_backup_slow_test.go
Added 2 tests that test repartitioning events, which shouldn't happen after the planned shutdown and during the temporary loss of members. In both cases repartitioning shouldn't happen.
=> test: Add tests for K8s repartitioning functionality

PROJECT, internal/webhookca/ca.go, main.go
=> [CN-646] Add webhook support for OLM

.github/scripts/utils.sh, .github/workflows/e2e-eks.yaml
Fixed the issue when the EKS cluster failed on the deletion step.
No more failing with deleting the EKS cluster
=> Fix step for deleting EKS cluster

.github/release-drafter-config.yml, .github/workflows/create-release.yaml
Fix create-release workflow and config file to create release automatically
=> ci: update release creation workflow

Makefile
=> Add optional print statement for Makefile tools

Makefile
=> Fix operator-sdk installation url

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, controllers/hazelcast/hot_backup_controller.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/rest/upload_service.go, internal/upload/upload.go
We now explicitly delete task after operator no longer needs it.
=> [CN-626] Explicitly delete hotbackup upload tasks

.github/workflows/backup-e2e-gke.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_persistence_test.go
- removes duplicated imports in the source code 
- removes unused vars in workflows
=> remove duplicated imports

.github/codecov.yml, .github/workflows/k8s-dist-tests.yaml, Makefile
Added test coverage tool on push event
=> [CN-651]- Added test coverage tool

controllers/hazelcast/wanreplication_controller.go
=> Fix wan controller import

.github/workflows/e2e-ocp.yaml, .github/workflows/k8s-dist-tests.yaml
=> Remove ocp tests from distribution tests

config/manager/manager.yaml, config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
=> [CN-700] Update CSV file for multinamespace and cluster wide operator support

Makefile
=> Add WATCHED_NAMESPACES variable to Makefile

test/e2e/helpers_test.go
=> Improve debug logging for e2e tests

.github/workflows/pr-label-checker.yml
Added PR labels checker workflow. When PR is opened and labeled or unlabeled, the workflow will check the PR if one of the required labels is present. If not- the bot will leave a comment and request the change.
=> Add pr label checker

.github/scripts/utils.sh, .github/workflows/e2e-eks.yaml, .github/workflows/generate-test-report.yaml, .github/workflows/nightly-ph-gke.yaml
Fix phone home, backup, and EKS tests. Updated test report links.
=> Fix phone home, eks and backup tests

api/v1alpha1/hazelcast_types.go, api/v1alpha1/hazelcast_validation.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, controllers/hazelcast/hazelcast_resources.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/phonehome/phonehome.go, test/e2e/config/hazelcast/config.go, test/e2e/e2e_suite_test.go, test/e2e/hazelcast_persistence_test.go, test/e2e/helpers_test.go, test/e2e/util_test.go, test/integration/hazelcast_webhook_test.go
Remove the support of `hostPath` for Hazelcast persistence
=> [CN-719] Remove hostPath support for persistence

test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_wan_slow_test.go, test/e2e/helpers_test.go, test/maploader/maploader.go
Change ResourceMemory from Gi to Mi to support the local run.
=> [CN-735] Change wan replication tests to accept Mb

api/v1alpha1/hotbackup_types.go, config/crd/bases/hazelcast.com_cronhotbackups.yaml, config/crd/bases/hazelcast.com_hotbackups.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
Additional comment about supported buckets and URI formats on HotBackupSpec API.
=> [CN-705] API comment about supported buckets and URI formats

test/integration/managementcenter_controller_test.go, test/integration/util_test.go
Fixes flaky mancenter integration test
`ManagementCenter CustomResource with ExternalConnectivity should handle ingress correctly`
=> Fixing flaky integration test

controllers/hazelcast/wanreplication_controller.go, test/e2e/config/managementcenter/config.go, test/e2e/hazelcast_wan_test.go, test/e2e/helpers_test.go
Fixed slow wan test failure and added the failing test case to the standard Wan e2e tests.
=> Fix wan slow test and add failing case to normal tests

test/e2e/config/hazelcast/config.go, test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_wan_slow_test.go, test/e2e/helpers_test.go, test/maploader/maploader.go
=> Update maploader function

.github/workflows/helm-chart-sync.yaml, test/e2e/hazelcast_backup_slow_test.go
Fixing interrupt backup slow e2e test:
`should interrupt external backup process when the hotbackup is deleted`
=> Fix backup interruption slow test

test/e2e/hazelcast_wan_slow_test.go
Fixed issue in WAN replication tests
=> Added SwitchContext to WAN replication tests

config/samples/_v1alpha1_managementcenter_ingress.yaml, controllers/hazelcast/hazelcast_status.go, controllers/managementcenter/managementcenter_controller.go, controllers/managementcenter/managementcenter_status.go, internal/util/util.go
Ingress and Route addresses will be present in Management Center external adresses status field.
=> Add external adress for ingress and route

api/v1alpha1/data_structure.go, api/v1alpha1/hazelcast_types.go, api/v1alpha1/map_types.go, api/v1alpha1/multimap_types.go, api/v1alpha1/topic_types.go, api/v1alpha1/wanreplication_types.go, config/crd/bases/hazelcast.com_caches.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/crd/bases/hazelcast.com_maps.yaml, config/crd/bases/hazelcast.com_multimaps.yaml, config/crd/bases/hazelcast.com_queues.yaml, config/crd/bases/hazelcast.com_replicatedmaps.yaml, config/crd/bases/hazelcast.com_topics.yaml, config/crd/bases/hazelcast.com_wanreplications.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
=> [CN-706] Improve comments in the API folder

api/v1alpha1/managementcenter_webhook.go, config/samples/_v1alpha1_managementcenter_route.yaml
=> Call validation function in MC webhook

test/e2e/hazelcast_high_availability_test.go
fixing the high availability test flakiness caused by Chaos Mesh
=> Fix high-availability test flakiness

.github/workflows/generate-test-report.yaml
This PR fixes the test report creation.
=> Fix condition for adding report in PR

api/v1alpha1/hazelcast_validation.go, config/samples/_v1alpha1_hotbackup_scheduled.yaml, test/integration/hazelcast_controller_test.go
- apply naming convention over test cases
- ordering test cases by CRs.
=> refactoring integration tests

api/v1alpha1/cache_types.go, api/v1alpha1/multimap_types.go, api/v1alpha1/queue_types.go, api/v1alpha1/replicatedmap_types.go, api/v1alpha1/topic_types.go, controllers/hazelcast/cache_controller.go, controllers/hazelcast/data_structure_controller.go, controllers/hazelcast/data_structure_status.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_status.go, controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_status.go, controllers/hazelcast/map_controller.go, controllers/hazelcast/map_status.go, controllers/hazelcast/multimap_controller.go, controllers/hazelcast/queue_controller.go, controllers/hazelcast/replicatedmap_controller.go, controllers/hazelcast/topic_controller.go, controllers/hazelcast/wanreplication_controller.go, controllers/hazelcast/wanreplication_status.go, controllers/managementcenter/managementcenter_controller.go, controllers/managementcenter/managementcenter_status.go, controllers/reconcile_options.go, internal/util/util.go, test/e2e/helpers_test.go
Status update functions for all CRs were updating all the fields in the status object. Now, update functions only updates explicit fields.
=> [CN-704] Remove side effects from status update functions

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/naming/constants.go
=> Update Hazelcast version to 5.2.3

.github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-ocp.yaml, .github/workflows/generate-test-report.yaml, .github/workflows/istio-e2e-gke.yaml, Makefile
Fixed OCP tests and removed the condition for setting up the CRD's for multiple workflows
=> [CN-789]- Improve OCP cleanup process and revise the "Add Test Report Summary To PR" step condition

.github/workflows/backup-e2e-gke.yaml, .github/workflows/cleanup-namespace.yaml, .github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/high-availability-e2e-gke.yaml, .github/workflows/istio-e2e-gke.yaml, .github/workflows/nightly-ph-gke.yaml
Fixes the incorrect input configuration in workflows. #671
=> [CN-770] Fixing the input configuration in cleanup workflows

.github/scripts/utils.sh, .github/workflows/backup-e2e-gke.yaml, .github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/high-availability-e2e-gke.yaml, .github/workflows/istio-e2e-gke.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml
Fixes by waiting for cleanup NS job before deleting the cluster. #671
=> [CN-770] Waits for cleanup NS job before deleting the cluster

internal/phonehome/phonehome.go, test/ph/phone_home_test.go
Bug fix for JVM Config phone home.
=> Fix JVM Config Phone Home

Makefile, test/e2e/hazelcast_backup_slow_test.go, test/e2e/helpers_test.go
This PR fixes two tests for Backup
=> Increased timeout for multiple BackupTests

.github/scripts/utils.sh
Fix issue with parsing allure report
=> [CN-781]- Fix issue with parsing JSON report files

.github/scripts/utils.sh, .github/workflows/e2e-ocp.yaml, .github/workflows/grafana-agent.yaml, .github/workflows/k8s-cluster-scope-tests.yml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/pull-request.yml, test/e2e/helpers_test.go, test/util.go
Update kube-state-metrics version and WAN replication workflow
=> Fix flaky tests

.github/workflows/nightly-wan-e2e-gke.yaml, test/e2e/hazelcast_wan_slow_test.go
=> Update waitForLBAddress function in WAN tests

api/v1alpha1/hazelcast_validation.go
removing TLS enterprise validation in Webhook
=> remove TLS enterprise validation in webhook

.github/workflows/k8s-dist-tests.yaml
=> Add link to the slack job message

.github/workflows/publish-release.yaml, config/samples/_v1alpha1_hazelcast.yaml, config/samples/_v1alpha1_hazelcast_expose_externally.yaml, config/samples/_v1alpha1_hazelcast_high_availability.yaml, config/samples/_v1alpha1_hazelcast_jvm_gc.yaml, config/samples/_v1alpha1_hazelcast_mc_monitoring_config.yaml, config/samples/_v1alpha1_hazelcast_persistence.yaml, config/samples/_v1alpha1_hazelcast_persistence_agent.yaml, config/samples/_v1alpha1_hazelcast_persistence_force_start.yaml, config/samples/_v1alpha1_hazelcast_persistence_restore.yaml, config/samples/_v1alpha1_managementcenter.yaml, config/samples/_v1alpha1_managementcenter_ingress.yaml, config/samples/_v1alpha1_managementcenter_no_pvc.yaml, config/samples/_v1alpha1_managementcenter_route.yaml, config/samples/_v1alpha1_managementcenter_tls.yaml
Removed the version from the sample files. This is required to avoid publishing new operator with an the old version of HZ and MC
https://github.com/k8s-operatorhub/community-operators/pull/2621/files#diff-9c63dea0a8576d4b1865f146427d9c3b34eb8977c2d1036e2c7eddfdc169d67eR47
=> Update sample files

main.go, test/integration/hazelcast_controller_test.go, test/integration/hazelcast_webhook_test.go, test/integration/managementcenter_controller_test.go, test/integration/suite_test.go
Setting up `kubeclient` in Integration test as well.
=> Kubeclient setup in Integration test

test/e2e/hazelcast_test.go, test/integration/hazelcast_controller_test.go, test/integration/hazelcast_webhook_test.go, test/integration/managementcenter_controller_test.go, test/integration/webhook_test.go
In test cases, wait until resources are created (license and TLS secrets in the current case).
=> fixing flaky tests caused by wehbook validation

api/v1alpha1/hazelcast_types.go, test/e2e/config/hazelcast/config.go
LicenseKeySecret -> LicenseKeySecretName 
the field name is forgotten to update in #722
=> Hotfix - update old struct field name to new one

api/v1alpha1/hazelcast_types.go, api/v1alpha1/hazelcast_validation.go, api/v1alpha1/jetjob_validation.go, internal/phonehome/phonehome.go, test/e2e/config/hazelcast/config.go, test/e2e/hazelcast_jetjob_test.go, test/integration/hazelcast_controller_test.go
=> [CN-800] Enable persistence for Jobs a.k.a Lossless Restart

internal/phonehome/phonehome.go
add missing TLS metrics to Phonehome
=> Phonehome TLS metrics

api/v1alpha1/jetjob_types.go, config/crd/bases/hazelcast.com_jetjobs.yaml, controllers/hazelcast/jetjob_controller.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
- Adding JetJobExecutionFailed status in JetJob CRD
- Renaming some JetJob status variable and values
=> Adding ExecutionFailed status in JetJob CRD

.github/workflows/test-and-release.yaml
Update preflight version to the "latest"
=> Update preflight tool to latest

api/v1alpha1/jetjob_validation.go
=> [CN-881] add validation for state change of the job

config/samples/_v1alpha1_hazelcast.yaml, controllers/hazelcast/mutate/mutate.go
Update the CRD when mutated in the reconciler
=> [CN-891] fix mutation detection for CR update

controllers/hazelcast/hazelcast_resources.go
Fix the operator update issue error: `create Pod hazelcast-2 in StatefulSet hazelcast failed error: Pod "hazelcast-2" is invalid: spec.containers[1].volumeMounts[0].name: Not found: "hazelcast-mtls-cert"`
=> [CN-903] update sidecar VolumeMount when STS gets updated

api/v1alpha1/jetjob_validation.go, test/integration/hazelcast_test.go, test/integration/jetjob_test.go, test/integration/util_test.go
Add secret validation which checks if the secret object is existing in JetJob CR
=> [CN-904] Secret validation of bucket config in JetJob CR

test/ph/phone_home_test.go, test/ph/util_test.go
Fixed Phone Home tests and "No more items in iterator" issues during the run.
=> Fixed Phone Home tests

api/v1alpha1/jetjob_validation.go
Run state validation only if state of the JetJob CR is changed
=> Fixes JetJob CR state validation

controllers/hazelcast/hazelcast_resources.go
Jet Job submission via client/CLC failed due to `Read-Only filesystem` errors because it tries to write into `/tmp` dir at the container.
Users can do Jet Job submission and UCD from client/CLC.
=> [CN-912] Volume mount for tmp dir

api/v1alpha1/hazelcast_types.go, api/v1alpha1/managementcenter_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/crd/bases/hazelcast.com_managementcenters.yaml, config/samples/_v1alpha1_hazelcast_jet.yaml, config/samples/_v1alpha1_jetjob.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/naming/constants.go
Update HZ and MC version to 5.3.1
forward-port of https://github.com/hazelcast/hazelcast-platform-operator/commit/2b6325765efc1e8d4f96ee117f1ecc1e06b85a22
=> Update HZ and MC version to 5.3.1

.github/workflows/publish-release.yaml, .github/workflows/test-and-release.yaml, Makefile
Fixed publish-release, test-and-release workflows and added `--use-image-digests` to avoid issue during release https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/troubleshooting.md#digest-pinning
=> Fix publish-release, test-and-release workflows

api/v1alpha1/jetjob_validation.go
rename JetJob state validation function to avoid confusion
=> Better naming on the JetJob state validation

apidocgen/main.go
=> Fix missing API ref docs

.github/workflows/backup-e2e-gke.yaml, .github/workflows/docs-release.yaml, .github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-ocp.yaml, .github/workflows/high-availability-e2e-gke.yaml, .github/workflows/istio-e2e-gke.yaml, .github/workflows/k8s-cluster-scope-tests.yml, .github/workflows/k8s-dist-tests.yaml, .github/workflows/multi-version-tests.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/pull-request.yml
Update actions/setup-go@v3 to actions/setup-go@v4
=> Update actions/setup-go@v3 to actions/setup-go@v4

.github/workflows/docs-release.yaml
These changes will add the lines into **nav.adoc** file into the release branch.
.Release Notes
* xref:release-notes.adoc[5.8]
=> [CN-918] Update docs-release.yaml workflow

test/e2e/hazelcast_test.go, test/e2e/helpers_test.go
Providing retry login in the common utility functions which have call to API server in E2E tests.
=> [CN-938] Fixing E2E test 'connection refused' error on GKE

Makefile
=> Omit skipped E2E test logs when running focused cases

.github/workflows/backup-e2e-gke.yaml, .github/workflows/cleanup-namespace.yaml, .github/workflows/delete-clusters.yaml, .github/workflows/docs-release.yaml, .github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-ocp.yaml, .github/workflows/generate-test-report.yaml, .github/workflows/grafana-agent.yaml, .github/workflows/helm-chart-sync.yaml, .github/workflows/high-availability-e2e-gke.yaml, .github/workflows/istio-e2e-gke.yaml, .github/workflows/k8s-cluster-scope-tests.yml, .github/workflows/k8s-dist-tests.yaml, .github/workflows/multi-version-tests.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/pre-release.yaml, .github/workflows/publish-release.yaml, .github/workflows/publish-snapshot.yaml, .github/workflows/pull-request.yml, .github/workflows/test-and-release.yaml
Now all Repository secrets are moved to the AWS Secrets manager.
=> [CN-929] Migrate secrets to AWS Secrets Manager

.github/workflows/e2e-ocp.yaml
=> Fix OCP workflow

.github/workflows/grafana-agent.yaml
Fixed the issue with Grafana setup on GKE cluster
=> Fixed secrets issue in Grafana workflow

.github/workflows/cleanup-namespace.yaml
Updated cleanup-namespace workflow to use proper secrets
=> Fix credentials in cleanup-namespace.yaml

go.mod, go.sum
Updating go-client version to the latest commit
=> Update go-client version to latest commit to test

api/v1alpha1/managementcenter_types.go, config/crd/bases/hazelcast.com_managementcenters.yaml, config/samples/_v1alpha1_hazelcast_jet_job_upload.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/naming/constants.go
Signed-off-by: devOpsHelm <devopshelm@hazelcast.com>
=> Update Hazelcast and MC version

go.mod, go.sum
=> Update Go client to v1.4.1

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/samples/_v1alpha1_hazelcast_jet.yaml, config/samples/_v1alpha1_hazelcast_jet_job_upload.yaml, config/samples/_v1alpha1_jetjob.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/naming/constants.go
Update Hazelcast version to v5.3.2
=> Update Hazelcast Version to 5.3.2

internal/backup/backup.go
=> Fix typo in Cluster Backup Error

Makefile, test/e2e/hazelcast_jetjob_test.go, test/e2e/hazelcast_jetjobsnapshot_test.go
Add missing test suite labels in Makefile
=> Add missing test suite labels

.github/workflows/docs-release.yaml, .github/workflows/pre-release.yaml, .github/workflows/publish-release.yaml, .github/workflows/test-and-release.yaml
Updated workflow to release Operator with patch version
=> [CN-1032] Updated workflow to release Operator with patch version

.github/workflows/nightly-wan-e2e-gke.yaml
Added Slack notification for WAN replication tests
=> Added Slack notification for WAN replication tests

.github/workflows/test-and-release.yaml
Replaced GKE to Kind for migration tests and add --platform amd64 to preflight to avoid issue with scanning images
=> [CN-1034]Replace GKE to KinD for migration tests and preflight command

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hazelcast_status.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/util/util.go, test/e2e/hazelcast_expose_externally_test.go, test/e2e/hazelcast_wan_slow_test.go, test/e2e/helpers_test.go, test/integration/hazelcastendpoint_test.go
Corresponding e2e tests are updated.
=> [CN-1017] Remove ExternalAddresses and WanAddresses from Hazelcast CR Status 

helm-charts/hazelcast-platform-operator/templates/_helpers.tpl
Trim each element of given chart variable `watchedNamespaces`
=> [CN-1069] Fix WatchedNamespaces passed as environment variable

.github/scripts/utils.sh, .github/workflows/istio-e2e-gke.yaml
=> [CN-1064] Fix Istio test workflow

test/e2e/hazelcast_expose_externally_test.go, test/e2e/helpers_test.go
need to break the loop that checks the map size after the actual map size is same as expected size
=> Fix WaitForMapSize function

.github/workflows/e2e-eks.yaml
Add inbound rule to the SecurityGroup of cluster nodes.
=> [CN-1106] Fix EKS workflow adding Ingress Rule to the Security Group of Nodes

.github/workflows/e2e-gke.yaml
Create firewall rule to accept external connections to the nodes.
=> [CN-1106] Fix GKE workflow creating Firewall Rule to allow external connections

.github/workflows/e2e-aks.yaml
Create NetworkSecurityGroup inbound rule to accept external connections to the nodes.
=> [CN-1106] Fix AKS workflow creating NSG rule to allow external connections

Makefile
It is simply an automation of remote deployment without tilt.
=> Add deploy-tilt target to Makefile

.github/dependabot.yaml, .github/workflows/test-and-release.yaml, test/e2e/hazelcast_soak_test.go, test/e2e/helpers_test.go
Fixed waitForMap function and updated dependabot configuration
=> Fixed waitForMap function and dependabot configuration

.github/scripts/utils.sh
Added option to edit last comment from PR bot about test status
=> Update PR commend bot

.github/workflows/generate-test-report.yaml, .github/workflows/k8s-dist-tests.yaml
Replaced 'sync' to 'cp' method for AWS S3 command and added default.s3.max_concurrent_requests 50 to speedup uploading
=> Replaced aws 'sync' to 'cp'

.github/workflows/k8s-dist-tests.yaml
Remove leftover codecoverage dependancy from k8s-dist-tests.yaml
=> Remove codecoverage dependency from  k8s-dist-tests.yaml

controllers/hazelcast/hazelcast_resources.go, test/integration/hazelcastendpoint_test.go
Leftover `HazelcastEndpoint` resources take place after disabling the exposeExternally as an update.
e.g:
```yaml
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
name: hz
spec:
clusterSize: 3
exposeExternally:
type: Smart
discoveryServiceType: LoadBalancer
memberAccess: LoadBalancer
```
update to
```yaml
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
name: hz
spec:
clusterSize: 3
```
The `Discovery` and `WAN` HazelcastEndpoints will stand with empty address.
```
NAME     TYPE        ADDRESS
hz       Discovery
hz-wan   WAN
```
=> Delete leftover HazelcastEndpoints

.github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-istio.yaml, .github/workflows/e2e-platform-misc.yaml, .github/workflows/e2e-platform-resilience.yaml
In the e2e test (including AWS, EKS ,Azure, Istio), we are allowing all IP addresses (0.0.0.0/0) as the source of network security. So this PR fixed this.
=> [CN-1127] Improve setup of security group and firewall rules for AKS, EKS, GKE

Makefile, config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml, test/e2e/helpers_test.go
Implemented this requirement https://app.partner.engage.redhat.com/e/es?s=940793389&e=60999&elqTrackId=d16e4b66f8074d27a3e8187b25322b95&elq=2e0ff0c46e254745a5b47d3f6b65d76f&elqaid=4115&elqat=1
Success run:
https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/8070990684/job/22049717502
=> [CN-1133]-Add new metadata annotations for OCP bundle

.github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/helm-chart-sync.yaml, .github/workflows/k8s-compatibility-test.yaml
Run E2E tests on different versions of Kubernetes clusters in order to test compatibility of the operator.
=> Compatibility test workflow

.github/workflows/e2e-gke.yaml, .github/workflows/e2e-kind.yaml, .github/workflows/k8s-compatibility-test.yaml
Run compatibility tests on `kind` cluster.
`GKE` cluster in #1053 is changed to `Kind`
=> [CN-632] Compatibility tests in Kind cluster

.github/workflows/test-and-release.yaml
Fix the issue with SDK installation:
=> Change the source for operator-sdk setup

.github/workflows/test-and-release.yaml
Added MC CR to upgrade test during release
=> [CN-1164]Added MC CR to upgrade test

test/e2e/backup_restore_test.go, test/e2e/client_port_forward_test.go, test/e2e/helpers_test.go
=> [CN-1163] Improve restore E2E tests

api/v1alpha1/hazelcast_webhook.go, api/v1alpha1/managementcenter_types.go, api/v1alpha1/managementcenter_webhook.go, config/webhook/manifests.yaml, helm-charts/hazelcast-platform-operator/templates/webhook.yaml, internal/controller/managementcenter/managementcenter_controller.go, test/integration/hazelcast_test.go, test/integration/managementcenter_test.go
Fix update validation for ManagementCenter `hazelcastClusters[*].tls.secretName`
=> Set optional TLS to nil if no required Secret provided [CN-1157]

test/e2e/platform_resilience_test.go, test/e2e/platform_wan_test.go
Added 2 tests that cover 3 scenarios:
* Ensure that the cluster doesn't lose any data in the Tiered Storage map during a Split Brain simulation
* Verify the Functionality of Active-Passive WAN Replication for Maps with Tiered Storage 
* Verify if WAN Sync properly works with TS
=> [CN-1118]Added tests for Tiered Storage

.github/workflows/test-and-release.yaml
Improved migration test output
=> Improve migration test output

Makefile
Fixed cluster scope test and include only tests that will run on KIND only
=> Added cluster_scope filtering to makefile

api/v1alpha1/wanreplication_types.go, config/crd/bases/hazelcast.com_wanreplications.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/config/hazelcast.go, internal/controller/hazelcast/hazelcast_resources.go, internal/controller/hazelcast/map_controller.go, internal/controller/hazelcast/wanreplication_controller.go, internal/hazelcast-client/wan_service.go, internal/protocol/codec/mc_add_wan_batch_publisher_config_codec.go, internal/protocol/types/merkle_tree_config.go, internal/protocol/types/request_add_map_config.go, test/e2e/helpers_test.go, test/e2e/wan_sync_test.go
Add Delta Wan Sync
Add possibility to configure `consistencyCheckStrategy` in WanReplication CR for Delta WAN Sync
=> Add Delta Wan Sync [CN-476]

test/integration/hazelcast_test.go
=> remove unnecessary it test

internal/phonehome/phonehome.go
=> [CN-1139] Resource limit CPU and Memory ph metrics

internal/phonehome/phonehome.go
=> [CN-1233] Convert resource metric types from String to Int

.github/workflows/e2e-ocp.yaml
Now when we install CRD’s (make install-crds) on OCP env there is a conflict:
`Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
`
So need to install it only once for OS env because CRD it’s a cluster scope.
=> [CN-1249]Fix installation CRD conflict in OCP workflow

api/v1alpha1/hazelcast_validation.go, internal/controller/hazelcast/hazelcast_resources.go, internal/naming/constants.go, test/integration/hazelcast_config_test.go
Webhook validation to check if the required `hazelcast` key exists in cm and the value is in a valid yaml structure.
=> Validate custom config key and yaml in WebHook

.github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-ocp.yaml
Disable status-badge update for workflow_dispatch events. It's only becomes available for jobs running on main branch
=> Disable status update for workflow_dispatch events

internal/controller/hazelcast/hazelcast_resources.go
Fixes the bug that causes restricted installation to fail.
=> [CN-1253] fix restricted installation

api/v1alpha1/hazelcast_validation.go
see: https://github.com/hazelcast/hazelcast-platform-operator/pull/1108#discussion_r1579285475
=> Update YAML package version in hazelcast-validation

README.md, config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
=> Update readme and CSV file for 5.12.0

.github/workflows/e2e-kind.yaml, .github/workflows/publish-helm-chart.yaml
Update command to get the kind image version to exclude -alpha or any other non-stable version
=> [CN-1299] Update getting Kind image version

.github/workflows/e2e-restricted-installation.yml, Makefile, test/e2e/map_test.go, test/e2e/multimap_test.go, test/e2e/queue_test.go, test/e2e/replicatedmap_test.go, test/e2e/topic_test.go
Added workflow that will run tests against [restricted setup ](https://docs.hazelcast.com/operator/5.11/get-started#:~:text=Restricted%20Installation)
=> [CN-1252] Added restricted setup workflow

.github/workflows/publish-release.yaml
* Added option to automatically enable auto-merge for 3 PR's and merge 1 PR in hazelcast-platform-operator repo
=> [CN-1291] Improve publish release process

.github/workflows/e2e-eks.yaml, .github/workflows/e2e-ocp.yaml
From time to time during test execution there is a race condition during deploying CRD's and one of the setup fails. So this PR will fix this
Here is successful [test](https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/9082611426/job/24960119639#step:11:33)
=> [CN-1298]Fix installing CRD's step in OCP and EKS workflow

test/e2e/platform_cpsubsystem_test.go
CP tests are failing with the Timeout waiting for the LB to be created. To fix the failure without increasing the timeout, it is better to use the port forwarding to access the HZ member
=> Use port-forward instead of ExposeExternally for CP tests [CN-1272]

internal/controller/hazelcast/hazelcast_resources_test.go, internal/controller/hazelcast/mutate/mutate_test.go, internal/protocol/codec/mc_change_cluster_state_codec.go, internal/protocol/codec/mc_get_cluster_metadata_codec.go
The PR contains examples of possible tests that must be added to the test-cases
=> Additional tests [CN-1286]

.github/workflows/e2e-istio.yaml, Makefile, test/e2e/expose_externally_test.go
We know that Istio tests will not pass after this PR due to issue CN-1305.
=> [CN-1194] Skip ExposeExternally test suite in Istio setup

.github/workflows/publish-release.yaml
Fix the issue in publish release
=> Fix publish release workflow

api/v1alpha1/map_validation.go
Fixes https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/9401886652
=> [CN-1307]fix wrong check

.github/workflows/e2e-istio.yaml
https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/9624323771/job/26547894981#step:5:38
=> Fix GKE cluster creating error in Istio workflow

.github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-istio.yaml, .github/workflows/e2e-platform-misc.yaml
The old action ( haythem/public-ip@v1.3) doesn't work properly and throws Error: read ECONNRESET so often.
=> Replace action for getting public ip of GH instance

.github/workflows/publish-release.yaml
Remove operators-prod repository from the release process
=> [CN-1316]Remove operators-prod repo from release process

.github/workflows/e2e-olm.yaml, .github/workflows/k8s-dist-tests.yaml, Makefile
Added OLM test suite but only for EE because we are going to remove OS soon.
=> [CN-1296] Added OLM test suite
