hazelcast/hazelcast-platform-operator

.github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-e2e-ocp.yaml
Example of run job on OCP: https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/1605940365
Example of run job on GKE: https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/1605940364
=> Use make clean-up-namespace job for CI pipelines

.github/workflows/pull-request.yml
Our PR builders were working correctly for PRs created in the main repository. However, the `safe-to-test` trigger was not working correctly for fork PRs. The reason is that E2E test jobs are in the middle of the job prerequisite graph and in the default settings jobs expect all the prerequisite jobs to be completed successfully. For label event trigger, the E2E jobs don't get triggered because we are skipping `linter` and `unit & integration test` jobs. To fix this, we need to ad `always()` function together with the correct conditions
=> Fix fork PR builder workflow

api/v1alpha1/hazelcast_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml
Changes the default value of the repository field in OpenAPI spec to OS Hazelcast
=> Change repository default in CRD

.github/workflows/pull-request.yml, controllers/hazelcast/hazelcast_resources.go, controllers/managementcenter/managementcenter_resources.go, controllers/platform/platform.go, main.go, test/e2e/e2e_suite_test.go, test/integration/suite_test.go
Changes:
- Added provider info to Platform struct, providers are `EKS`, `GKE` and `AKS`.
- Added config to the Platform resolver client. It used to use Kubeconfig as default one, I set its config to the Manager's one.
=> [CN-262] Add Kubernetes provider info into platform struct

.github/workflows/redhat-connect-release.yaml, config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
Changes:
- Add required fields into CSV file and fix `minKubeVersion`.
- Use image digest instead of tag in bundle CSV file.
- Use makefile to clean up after E2E tests.
- Change bundle package name for marketplace, new one has `rhmp` suffix.
- Add required annotations to CSV for marketplace.
- Add default channel annotations to annotation.yaml.
=> [CN-303] Fix Bundle Release Pipelines for Red Hat Release

.github/workflows/redhat-connect-release.yaml
The former digest actually was the image ID.
=> Fix image digest for Red Hat Operator image

test/integration/hazelcast_controller_test.go
Update() method in tests observers Conflicted Update error in some cases.
This PR adds functionality to repeat updates in case of such event (repeatedly calling Get() and Update()).
=> Repeat conflicted updates in test

test/ph/phone_home_test.go
In Phone Home E2E tests, MC test did not had enough checks to ensure that the phone home was sent. Checking annotation is set ensures that at least MC sent phone home request is being sent in a different goroutine.
=> Fix MC Phone home test

controllers/managementcenter/managementcenter_resources.go
The Readiness probe using `HTTPGet` for endpoint `/health` does not prove the Spring web started it shows that Jetty is started listening on port 8081.  This PR changes readiness probe into `TCPSocket` for port `8080`.
=> Fix Readiness probe for MC container

.github/workflows/redhat-connect-release.yaml
Since we decided we don't publish Operator to the marketplace, this part was removed from the CI process. Also, it's unnecessary to run e2e tests during the publishing process because it takes a lot of time, and if we need it, we have a separate job for it. 
no ci
=> [CN-318 | CN-317] Removed publishing to marketplace and running e2e test during publishing process

api/v1alpha1/hazelcast_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, test/e2e/config/hazelcast/config.go
The tests contained the hardcoded name of `standard` ClassName which is the default one for GKE but is not present for EKS and AKS
=> E2E tests: remove storage class to use the default one

.github/workflows/create-release.yaml, .github/workflows/dockerhub-release.yaml, .github/workflows/redhat-connect-release.yaml
1. I just added DEVOPS_GITHUB_TOKEN to trigger dockerhub and redhat publish workflows.
2. Added ref: 'main' to updated versions to the latest snapshot and fix this error: 
```
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/hazelcast/hazelcast-platform-operator'
Error: Process completed with exit code 1.
```
=> Fix create release workflow

controllers/hazelcast/hazelcast_resources.go, controllers/managementcenter/managementcenter_resources.go
Added config for HZ and MC following the documentation:
https://docs.hazelcast.com/management-center/5.1/deploy-manage/phone-homes#disabling-the-collection-of-usage-analytics
https://docs.hazelcast.com/hazelcast/5.1/phone-homes
=> [CN-321] Add phone home config for HZ and MC pods

.github/workflows/dockerhub-release.yaml, .github/workflows/redhat-connect-release.yaml
Changes:
- Remove job for after release push in "dockerhub-release.yaml", which
reverted release version to latest-snapshot. We will not need it
anymore since we are releasing from a ephemeral branch.
- Fix slack notify job and add it into dockerhub-release.yaml
- Fix syntax error in redhat-connect-release.yaml, fail-fast requires
matrix to be present.
=> Prepare workflows for release branch

.github/workflows/docs-release.yaml, .github/workflows/publish-snapshot.yaml, Makefile, apidocgen/main.go
The API reference doc generation code is based on https://github.com/oracle/coherence-operator/tree/master/docgen. This code generates the API reference by going over the structs in the `api/` directory.
Changes to the code:
- General refactor of the structs and functions in the code.
- Use kubebuilder tags for filling `required` column instead of `json` tags.
- Use kubebuilder tags to fill `default` column.
- Add String types into the API ref with columns `value` and `description`.
I also added steps into `docs-release.yaml` and `publish-snapshot.yaml` to push the new API ref doc into docs repository.
To Decide:
=> [CN-273] Add API reference doc generation code

.github/workflows/nightly-e2e-gke.yaml
Fixes the error `
On 2022-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name. We strongly advise updating your GitHub Action YAML from: uses: 'google-github-actions/setup-gcloud@master' to: uses: 'google-github-actions/setup-gcloud@v0' While not recommended, you can still pin to the "master" branch by setting the environment variable "SETUP_GCLOUD_I_UNDERSTAND_USING_MASTER_WILL_BREAK_MY_WORKFLOW_ON_2022_04_05=1". However, on 2022-04-05 when the branch is renamed, all your workflows will begin failing with an obtuse and difficult to diagnose error message. For …
=> Update gcloud setup step to v0.3.0

controllers/hazelcast/hazelcast_config.go, controllers/hazelcast/hazelcast_config_local_run.go
We already log errors in operator so we can suppress errors from the library.
=> [CN-214] Disable error logs for Hazelcast go-client

controllers/hazelcast/hazelcast_status_controller.go
InitialBackoff and MaxBackoff are of type `time.Duration` which means the current configuration was in nanoseconds. This fixes them into seconds.
=> [CN-220] Fix client connectionStrategy to seconds

.github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml
We skip delete-cluster step if there is a failure. 
We need to extend this condition to cleanup-namespace step too.
=> Skip cleanup step if there is a failure before

controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_status.go, controllers/hazelcast/hazelcast_status_controller.go
Changes:
- Fixed race condition between `initHzClient` and `shutdown`, where if `StartNewClientWithConfig` takes too much time reconcile function gets blocked for a very long time.
- Improved Hazelcast status messages about client's connection to the cluster. 
TODO:
=> [CN-220] Improve operator status for client

Makefile, bundle.yaml
- upgrade kustomize version to 4.5.3
- use 'go install' instead of 'go get' because go get no longer builds or installs packages in module-aware mode(https://tip.golang.org/doc/go1.18#go-command)
=> Makefile updates for Go 1.18 support and Apple silicon

.github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-ph-gke.yaml
Current triggers for Slack jobs in some of the workflows, only get triggered from the `delete-cluster` job. This was OK, when we were not deleting the clusters if an E2E test failed. However, currently `delete-cluster` jobs always run and it will not trigger the Slack notify job even though the E2E tests fail.
=> Fix Slack notify job triggers

test/e2e/e2e_suite_test.go, test/ph/ph_suite_test.go
E2E tests in the CI sometimes fail when applying the CRDs from the code because we are running `EE` and `OS` tests at the same time in the same cluster. 
CRD creation step in the code is not necessary since we are doing it before running the tests.
An example test failure is here https://github.com/hazelcast/hazelcast-platform-operator/runs/6190621996?check_suite_focus=true
=> Remove CRD creationg from E2E test code

controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_controller_test.go
Fix the bug when the `scheduled` part is removed from the `HotBackup CR`. When so, the schedule must be removed, and instead the `HotBackup` must be triggered immediately
=> fix scheduled update

controllers/hazelcast/hazelcast_resources.go, controllers/managementcenter/managementcenter_resources.go, test/integration/hazelcast_controller_test.go, test/integration/managementcenter_controller_test.go
With the current changes, `persistence` is the only field that updates are not reflected in the operator.
=> [CN-395] Make resources and scheduling spec fields updatable for HZ and MC

test/e2e/util_test.go
Fix the small timeout for removing CR's causes the issue when tests start to fail for AWS and OCP
[no ci]
=> CN-356-Increase timeout

test/e2e/management_center_test.go
Increase timeout for MC from 2 to 5 minutes to prevent flaky tests  (OCP env)
[no ci]
=> Increase timeout for MC from 2 to 5 minute to prevent flaky tests

Makefile
By default, Ginkgo only emits full stack traces when a spec panics. When a normal assertion failure occurs, Ginkgo simply emits the line at which the failure occurred. So just to be able to get a full stack trace the "--trace" option was added to e2e tests.
=> Added '--trace' to expose more information about failure in e2e tests

.github/workflows/docs-release.yaml
Fixed docs-release.yaml workflow which is doesn't create a new JSON object for the new operator version
=> [CN-376]-fixed docs release workflow

api/v1alpha1/hazelcast_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, test/e2e/e2e_suite_test.go, test/e2e/hazelcast_persistence_test.go, test/e2e/hazelcast_test.go
Changes:
- Increased timeout for external API errors test
- Platform was not set for all parallel running processes, now it is set.
- Increased timeout for restore status check
- Using agent version 0.1.3 for GCP Bucket fixes. GCP buckets were opened by disregarding the prefix the in query. Now, prefix is also applied.
=> Fix multiple E2E test errors

test/e2e/custom_resource_test.go, test/e2e/e2e_suite_test.go, test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_expose_externally_test.go, test/e2e/hazelcast_map_persistence_test.go, test/e2e/hazelcast_map_test.go, test/e2e/hazelcast_persistence_test.go, test/e2e/hazelcast_test.go, test/e2e/hazelcast_wan_test.go, test/e2e/helpers_test.go, test/e2e/management_center_test.go, test/e2e/options_test.go, test/e2e/util_test.go
Changes:
- Used unique resource names for each test case. 
- Formatted AfterEach Block to reuse code.
=> [CN-447] Use unique names per test case

Makefile
`clean-up-namespace` directive was not able to delete all the CRs that were created by the tests. It was caused by some of the CRs` finalizers not being removed. Now, finalizers are successfully removed and namespace is deleted.
=> [CN-452] Fix clean-up-namespace directive

.github/workflows/pull-request.yml
Currently when the workflow is cancelled `create-gke-cluster` workflow does not get cancelled. With the following changes it gets cancelled.
=> Fix PR builder create-gke-cluster trigger

test/e2e/helpers_test.go
In Eventually block of function CreateHazelcastCR, there is an Expect block which makes the logic of Eventually block obsolete. Related error is here https://github.com/hazelcast/hazelcast-platform-operator/runs/7211567958?check_suite_focus=true
=> [CN-452] Fix CreateHazelcastCR function

.github/newrelic/newrelic-values.yaml
We need to disable `lowDataMode` for logging as we need the `k8s` attributes included in the logs (such as pod name, namespace, etc.). On the other hand, `nri-infrastructure` data should be in the `lowDataMode` as this is the main source of data ingestion
=> disable lowDataMode for logging

.github/newrelic/newrelic-values.yaml
As for NewRelic settings, I have disabled scraping the needed GKE clusters data, which was the main reason for the huge amount of data ingestion. Without this, the `lowDataMode` is not needed as the data ingestion is less than 1GB a day for all the clouds
=> Disable lowDataMode as not needed

controllers/hazelcast/hazelcast_resources.go
Always use structured logging for easier cloud logging integrations.
Example:
```json
{"time":"2022-07-25T09:08:43,462", "logger": "com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask", "level": "INFO", "msg": "[10.244.0.5]:5701 [dev] [5.1.2] Received auth from Connection[id=19, /10.244.0.5:5701->/172.18.0.1:32840, qualifier=null, endpoint=[172.18.0.1]:32840, remoteUuid=4dad2ad4-d082-4c06-888f-4861d00ce9d9, alive=true, connectionType=GOO, planeIndex=-1], successfully authenticated, clientUuid: 4dad2ad4-d082-4c06-888f-4861d00ce9d9, client name: hz.client_1, client version: 1.2.0 "}
```
=> [CN-446] Format Hazelcast Pod logs as JSON

controllers/hazelcast/client/client.go, controllers/hazelcast/config/hazelcast_config.go, controllers/hazelcast/config/hazelcast_config_local_run.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hazelcast_resources_test.go, controllers/hazelcast/hazelcast_rest_client.go, controllers/hazelcast/hazelcast_status.go, controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_controller_test.go, controllers/hazelcast/hot_backup_status.go, controllers/hazelcast/map_controller.go, internal/backup/backup.go, internal/rest/hazelcast_service.go
In addition to creating `backup` package we needed to move `client` and `config` to new packages to avoid circular dependency.
Retry logic will try to rerun http request only if it was successful http request but Hazelcast status is other than `success`.
=> [CN-473] Add backup package with retry logic

test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_expose_externally_test.go, test/e2e/hazelcast_map_custom_class_test.go, test/e2e/hazelcast_map_persistence_test.go, test/e2e/hazelcast_map_test.go, test/e2e/hazelcast_persistence_test.go, test/e2e/hazelcast_test.go, test/e2e/hazelcast_wan_test.go, test/e2e/helpers_test.go
In Ginkgo skipped tests still run `afterEach` function and they call the deletion functions. At the start of the test, when 2 Ginkgo processes start running test if one of them runs a skipped test first it sometimes deletes the resources of the other one because skipped tests do not call `setLabelAndCRName` function which means the `lookup keys` and `labels` variables are empty. When `deleteAllOf` is called with empty labels it deletes all of the existing resources because every resources matches the empty label. Now, skipped tests do not run the clean up code.
=> [CN-472] Remove skipped tests from running afterEach block

controllers/hazelcast/hazelcast_resources.go
Currently, the `volumes` method called in `createOrUpdate` function in StatefulSet reconciler function overrides the default mode of Config Map volumes as follows. This causes the Hazelcast reconciler to get triggered indefinitely. With the changes this is no longer the case.
```
2022-08-04T17:12:03.555+0300    INFO    controllers.Hazelcast   Operation result        {"hazelcast": "default/hazelcast", "Statefulset": "hazelcast", "result": "updated"}
Change log is [
{
"type": "update",
"path": [
"Spec",
"Template",
"Spec",
"Volumes",
"0",
"VolumeSource",
"ConfigMap",
"DefaultMode"
],
"from": 420,
"to": null
}
]
2022-08-04T17:12:03.620+0300    INFO    controllers.Hazelcast   Operation result        {"hazelcast": "default/hazelcast", "Statefulset": "hazelcast", "result": "updated"}
Change log …
```
=> Add configMap Volume default mode

internal/util/util.go
This should avoid loggoing not found error when we wait for StatefulSet:
```
2022-08-11T12:31:14.696+0200    ERROR   controller-runtime.manager.controller.hazelcast Reconciler error        {"reconciler group": "hazelcast.com", "reconciler kind": "Hazelcast", "name": "hazelcast", "namespace": "default", "error": "StatefulSet.apps \"hazelcast\" not found"}
```
=> [CN-478] Ignore NotFound errors when waiting for StatefulSet

test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_expose_externally_test.go, test/e2e/hazelcast_map_persistence_test.go, test/e2e/hazelcast_map_test.go, test/e2e/hazelcast_map_user_code_test.go, test/e2e/hazelcast_persistence_test.go, test/e2e/hazelcast_test.go, test/e2e/hazelcast_wan_test.go
Remove Hazelcast resource wait condition from E2E test clean up. The reason for the change is the Hazelcast resource deletion takes too long when using `exposeExternally` feature in AWS and OCP.
=> Do not wait for Hazelcast deletion in E2E test cleanup

.github/actions/operator-tests/action.yml, .github/workflows/docs-release.yaml, .github/workflows/redhat-connect-release.yaml, Dockerfile, api/v1alpha1/hazelcast_types.go, api/v1alpha1/managementcenter_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/crd/bases/hazelcast.com_managementcenters.yaml, config/samples/_v1alpha1_hazelcast.yaml, config/samples/_v1alpha1_hazelcast_expose_externally.yaml, config/samples/_v1alpha1_hazelcast_persistence.yaml, config/samples/_v1alpha1_hazelcast_persistence_agent.yaml, config/samples/_v1alpha1_hazelcast_persistence_restore.yaml, config/samples/_v1alpha1_managementcenter.yaml, go.mod, go.sum, internal/naming/constants.go
New versions:
- Go: 1.16 -> 1.17
- Hazelcast: 5.1.2 -> 5.1.3
- Management Center: 5.1.3 -> 5.1.4
- Hazelcast Go Client: 1.2.0 -> 1.3.0
=> Update Go, Hazelcast, MC and Hazelcast Go Client versions

api/v1alpha1/hazelcast_types.go, api/v1alpha1/map_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/crd/bases/hazelcast.com_managementcenters.yaml, config/crd/bases/hazelcast.com_maps.yaml, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hazelcast_status.go, controllers/hazelcast/map_controller.go, controllers/hazelcast/map_status.go, internal/util/util.go, test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_map_persistence_test.go, test/e2e/hazelcast_persistence_test.go, test/e2e/hazelcast_test.go, test/e2e/helpers_test.go
Changes done to both
- Hazelcast CR: before deletion it deletes dependent Map and HotBackup CRs.
- Map CR: before deletion it deletes dependent WanReplication CRs.
=> [CN-475] Add finalizer logic for deleting dependent child CRs

controllers/hazelcast/client/client.go
While the operator is on stuck state, I got the thread dumps and found a deadlock. It seems the reason of the idle issue is this deadlock. In [client UpdateMembers](https://github.com/hazelcast/hazelcast-platform-operator/blob/84b24ea233482eb617f0847398cd1057f2a264be/controllers/hazelcast/client/client.go#L256-L259) function and in [client shutdown](https://github.com/hazelcast/hazelcast-platform-operator/blob/84b24ea233482eb617f0847398cd1057f2a264be/controllers/hazelcast/client/client.go#L196-L197) function, same mutex is tried to be locked. I fixed the issue by using another mutex for `client.Status` field. The only update operation on  `client.Status` field occurs in UpdateMembers function.
```
goroutine 18662 [semacquire, 7 minutes]:
sync.runtime_SemacquireMutex(0x2, 0x2b, 0x188e020) …
```
=> [CN-507] Fix operator idle issue

.github/workflows/generate-test-report.yaml
Sometimes cleanup workflow is failed because publishing takes too much time due to size of reports. So need to increase this timeout from 5m to 10m
=> Increased the cleanup timeout for removing 'pages-build-deployment' 

controllers/hazelcast/map_controller.go, test/e2e/hazelcast_user_code_test.go
For the Map CR we are using `MapName` function to get map's name but in some places kubernetes default `GetName` function is used. I just replaced them with `MapName`.
`MapName` checks if spec.Name is not empty. If so return it. If not, return metadata.Name
`GetName` returns metadata.Name
=> Fix wan nightly test failures

controllers/hazelcast/hazelcast_resources.go
When agent is added to the Hazelcast member pods, Kubernetes discovery plugin adds `member-ip:5701` and `member-ip:8080` into member endpoints instead of only `member-ip:5701`. This in turn becomes a problem when the plugin tries to enrich members with external IPs. It can no longer map endpoints to external IPs one to one, so no member gets an external IP. 
With the changes, this problem is fixed.
=> Remove agent port from the discovery service

.github/workflows/nightly-e2e-ocp.yaml
Currently, we use `imagePullPolicy=IfNotPresent ` and since the OCP cluster doesn't remove after each test run, there always left the old hazelcast/hazelcast-platform-operator:latest-snapshot. So to avoid the issue, the cleanup image operation was added. 
Now all the unused images will be removed after each test run on the OCP cluster.
=> Add cleaning up unused images from the cluster

bundle.yaml, config/rbac/role.yaml, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go
Cluster-wide secret list/get privileges to namespaced ServiceAccount is removed.
New namespaced Role and RoleBinding are created and passed to namespaced serviceaccount of hazelcast cluster to grant secret access.
=> Add Namespaced Role for secret access

.github/workflows/nightly-e2e-eks.yaml
According to the documentation if you plan to deploy workloads that use Amazon EBS volumes in a new **1.23 cluster**, install the Amazon EBS CSI driver in your cluster before deploying the workloads your cluster.
=> Setup CSI driver to support EBS volumes on EKS cluster

.github/workflows/community-operator-tests.yaml
Added env variable `OPP_RELEASE_INDEX_NAME: "catalog_tmp"` that fixes below issue:
```
TASK [operator_index : Remove 'hazelcast-platform-operator' operator to index image kind-registry:5000/test-operator/catalog:latest] ***
fatal: [localhost]: FAILED! => changed=true 
cmd: /tmp/operator-test/bin/opm index rm -c podman --operators hazelcast-platform-operator --tag kind-registry:5000/test-operator/catalog:latest --permissive --from-index kind-registry:5000/test-operator/catalog:latest
```
=> Fixed "orange" test suite for community operator

test/e2e/hazelcast_backup_slow_test.go, test/e2e/hazelcast_persistence_test.go
With this change each persistence/backup test will use empty PV and we will be sure we restored from backup folder.
=> [CN-562] Delete PV/PVC before we create new cluster

Dockerfile
Red Hat base images (including the RHEL and UBI images) are periodically rebuilt to address security vulnerabilities within them, but there can be a lag between when Important vulnerabilities arise and when they are addressed via a UBI release. This can lead to an image being built on the UBI, for example, failing security vulnerability scans in between release cycles of the UBI itself.
https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/containers/troubleshooting.md#ubi-minimal
=> Update the Dockerfile to avoid failing security vulnerability scans

.github/workflows/backup-e2e-gke.yaml, .github/workflows/certification-tests-and-release.yaml, .github/workflows/docs-release.yaml, .github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/publish-release.yaml, .github/workflows/pull-request.yml
Starting 1st June 2023, workflows using set-output commands via stdout will fail with an error. Currently, we have a lot of warnings in our workflows
=> Update deprecated set-output commands

.github/workflows/generate-test-report.yaml
Sometimes "nightly-e2e-test" fails because of timeout for cleanup "pages-build-deployment". So the solution is to increase up to 20min to wait until the test report is deployed
=> ci: increase timeout for cleanup "pages-build-deployment" workflow

Makefile, api/v1alpha1/hazelcast_types.go, api/v1alpha1/managementcenter_types.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/crd/bases/hazelcast.com_managementcenters.yaml, config/rbac/role.yaml, config/samples/_v1alpha1_hazelcast.yaml, config/samples/_v1alpha1_hazelcast_expose_externally.yaml, config/samples/_v1alpha1_hazelcast_persistence.yaml, config/samples/_v1alpha1_hazelcast_persistence_agent.yaml, config/samples/_v1alpha1_hazelcast_persistence_restore.yaml, config/samples/_v1alpha1_managementcenter.yaml, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, internal/naming/constants.go, test/integration/hazelcast_controller_test.go
allow watch verb on StatefulSets resources, so Hazelcast can monitor StatefulSet spec & status changes and make informed decisions about member/cluster shutdown and startup
=> [CN-594] allow watch verb on statefulsets resources

controllers/hazelcast/hot_backup_controller.go
startBackup function was returning no errors when one of the members failed with an error if the return value of the cancel function was nil.
=> Fix error hiding in startBackup function [5.5]

bundle.yaml, config/rbac/role.yaml, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go
Currently members are getting the following error:
```
Exception in thread "hz-k8s-sts-monitor" com.hazelcast.spi.exception.RestClientException: Failure executing: GET at: https://kubernetes.default.svc/apis/apps/v1/namespaces/test-operator-nightly-ee/statefulsets. Message: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"statefulsets.apps is forbidden: User \"system:serviceaccount:test-operator-nightly-ee:hp-7-y6cier\" cannot list resource \"statefulsets\" in API group \"apps\" in the namespace \"test-operator-nightly-ee\"","reason":"Forbidden","details":{"group":"apps","kind":"statefulsets"},"code":403}. HTTP Error Code: 403
```
=> [CN-594] Add list statefulset permission for member role [5.5]

controllers/hazelcast/hazelcast_resources.go
This is a temporary fix for Hazelcast discovery plugin where the first member tries to assume the address of the discovery service load balancer, because there are no members running at that time. With the additional IP it can no longer assume the IP address.
=> [CN-614] Add additional port to the LB discovery service

README.md, config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
Added the next feature to readme file and hazelcast-platform-operator.clusterserviceversion.yaml:
* User Code Deployment feature, which allows you to deploy custom and domain classes to Hazelcast members
* External Backup to cloud storage with a possibility to schedule it and restore the data accordingly
* WAN Replication feature when you need to synchronize multiple Hazelcast clusters, which are connected by WANs
* Support the several data structure like Map, Topic, MultiMap, and ReplicatedMap
* Executor Service and Entry Processor support
=> Add new feature to README.md file

controllers/hazelcast/fakes_test.go, controllers/hazelcast/hazelcast_status.go, controllers/hazelcast/hot_backup_controller_test.go, internal/backup/backup.go, internal/hazelcast-client/config.go, internal/hazelcast-client/config_local_run.go, internal/hazelcast-client/status_service.go, internal/local_backup/local_backup.go
Created unit tests are taken from the deleted tests in  #381
Also added unit test for the case where one member's timed member state returns failure, this case is created for the fixed issue #445
=> [CN-563] Add unit tests for HotBackup Reconciler

Dockerfile, Makefile, config/manager/kustomization.yaml
After the previous release `5.4`, the release branch was merged to the main branch without the changes in several files like Dockerfile, Makefile and kustomization file. It was merged `5.4` version instead of `latest-version` in some properties. This is became the reason why the correct bundle can't be created using the workflow file `Create Release`.
=> Revert 5.4 version to latest-snapshot in Dockerfile, Makefile, kustomization.yaml 

test/e2e/hazelcast_backup_slow_test.go
Fix the issue when the Backup test fails.
=> Disable PVC removal for PVC based tests

Dockerfile, Makefile, bundle.yaml, config/manager/kustomization.yaml
After the previous release 5.4, the release branch was merged to the main branch without the changes in several files like Dockerfile, Makefile and kustomization file. It was merged 5.4 version instead of latest-version in some properties. This is became the reason why the correct bundle can't be created using the workflow file Create Release.
=> Revert 5.4 version to latest-snapshot in Dockerfile, Makefile, kustomization.yaml file

.github/scripts/utils.sh, .github/workflows/certification-tests-and-release.yaml, .github/workflows/publish-release.yaml
1. Now, the images will be auto-published with the enabled option in the certified project
2. Update OCP version from 4.6 to 4.8 because OCP4.6 and OCP 4.7 are ends of life recently, and the pipeline tool removed their support; if you still set "com.redhat.openshift.versions: v4.6 ", the RedHat pipeline test would fail.
3. Removed the script responsible for publishing
=> ci: update workflow to support auto-publishing on RedHat site

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/create-release.yaml, .github/workflows/pull-request.yml, .github/workflows/release-drafter-config.yml
This new functionality will allow creating of release notes automatically based on labels which are will automatically add base on the commit or branch name.
=> ci: add autolabeling option and draft release creator

.github/PULL_REQUEST_TEMPLATE.md, .github/release-drafter-config.yml
Currently, when new features develop, we almost always add new tests. Release drafter automatically sets the tag “tests” to the 'feature' PR.
Now, if the developer adds a new test and feature at the same time, such PR won't mark it as a "test" automatically.
=> ci: Remove 'test/*' path from release drafter labeling config

controllers/hazelcast/hazelcast_resources.go, controllers/managementcenter/managementcenter_resources.go
PR also contains addition of some field default values into containers because they triggered an update to statefulset every time the reconciler got triggered due to fields being overridden by the operator.
=> [CN-561] Add security context to all containers for hostPath permissions

internal/protocol/types/event_journal_config.go, internal/protocol/types/hot_restart_config.go, internal/protocol/types/merkle_tree_config.go, internal/protocol/types/request_add_map_config.go
In `addMapConfig` method there were some nullable fields that returned error when given as null. Those were `HotRestartConfig`, `EvictionConfig` , `EventJournalConfig` and `MerkleTreeConfig`. The issue https://github.com/hazelcast/hazelcast/issues/21182 was fixed.
Removed temporary codec solution for fixed Hazelcast issue https://github.com/hazelcast/hazelcast/issues/21182.
=> [CN-381] Remove temporary codec solution with the fixed version

Makefile, apidocgen/main.go
Fix the generation of the API doc for the nested inline data structs.
Instead of generating the docs file by file, the changes tend to generate it for the entire package making the data structs located in a different file accessible
The API ref doc will be generated correctly
=> Fix API doc generation

.github/workflows/nightly-wan-e2e-gke.yaml
Added go-version 1.19 setup to Operator Deploy step. Before this update, Nightly WAN tests failed.
WAN replication tests become stable
=> [CN-636] add go-version 1.19 to deploy operator step

.github/scripts/utils.sh, .github/workflows/backup-e2e-gke.yaml, .github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-e2e-kind.yaml, .github/workflows/nightly-e2e-ocp.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml
The old method which is restarting failed nodes doesn't work. The current method checks provider "instanceState" for all machines. If it's not 'running' then the EC2 instance will be **stopped** -> then wait until it returns stopped for all elements. It will poll every 15 seconds until a successful state has been reached. This will exit with a return code of 255 after 40 failed checks -> Afterward, it **start** the instance and waits until a successful state has been reached.
OCP nightly tests will be more stable and shouldn't fail if some of the nodes are not ready.
=> ci: add ocp restart mechanism

.github/workflows/nightly-e2e-kind.yaml
From time to time metallb installation failed, and it causes the Nightly KinD test suite to fail. The solution is: to use VM Ubuntu-22.04, update metallb version to v0.13.7, and added a retry installation step in case of step failed (3 attempts with a 5-minute timeout for the whole setup operation). 
KinD nightly tests become stable.
=> [CN-633] ci/fix metallb installation on KinD

.github/workflows/pull-request.yml
Added the possibility to run PR builder when something is going to be merged to the **"release/**"** branch.
PR builder job will be run not only against the "main" branch
=> [CN-611] Add "release/" branch trigger for PR builder

test/e2e/hazelcast_expose_externally_test.go, test/e2e/helpers_test.go
It fixes the failing expose externally tests on EKS.
Fixed tests:
- `[It] should create Hazelcast cluster exposed with LoadBalancer services and allow connecting with Hazelcast smart client` 
The reason why this test gets failed is that the hostname of the service created by EKS has more than one public IP addresses.
=> [CN-637] fixing expose externally tests on EKS

.github/workflows/backup-e2e-gke.yaml, .github/workflows/generate-test-report.yaml, .github/workflows/nightly-e2e-aks.yaml, .github/workflows/nightly-e2e-eks.yaml, .github/workflows/nightly-e2e-gke.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/pull-request.yml, Makefile, test/e2e/helpers_test.go
- Renamed ${GITHUB_RUN_NUMBER} to {{ github.run_number }}. The old format causes the error in certain workflows `Error: google-github-actions/get-gke-credentials failed with: not found:`
- Replaced method of getting credentials from "gcloud container clusters get-credentials" to "google-github-actions/get-gke-credentials" action
- Added _DOCKER_BUILDKIT=1_ property to the docker build command, which decreased the build time by more than 30%
- Increased timeout for checking map status in function assertMapStatus() that fix flakiness  some of the GKE tests
- WAN replication and PH workflows become more stable
- Build docker image time decreased by 30%
=> Fix WAN replication and PH workflows

test/e2e/hazelcast_persistence_test.go
Multiple tests were using the same host path for their backup processes in hostPath E2E tests. This caused occasional test failures.
=> Fix hostPath E2E tests' paths for multiple tests

controllers/hazelcast/fakes_test.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/map_controller.go, internal/hazelcast-client/client_registry.go, internal/hazelcast-client/status_service.go
Changes:
- Added client recreation logic for times client cannot access the cluster
- Fixed the nil pointer bug in UpdateMembers function 
Operator will restart the Hazelcast client when the cluster is inaccessible.
=> [CN-634] Add client recreation logic for times client cannot access the cluster

controllers/hazelcast/hazelcast_resources.go, internal/config/hazelcast.go
data-load-timeout-seconds is deprecated here [hazelcast/hazelcast-full-example.yaml at master · hazelcast/hazelcast](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml#L2630)
`hazelcast.Spec.Persistence.DataLoadTimeoutSec` parameter won't be settable anymore.
=> [CN-648] rm h.Spec.Persistence.DataLoadTimeoutSec

api/v1alpha1/data_structure.go, api/v1alpha1/wanreplication_types.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/wanreplication_controller.go, controllers/hazelcast/wanreplication_status.go, internal/config/hazelcast.go, internal/hazelcast-client/wan_service.go, test/e2e/hazelcast_wan_test.go, test/e2e/helpers_test.go
Changes:
- Added `persisting` state to WanReplication status and implemented ConfigMap persistence logic to WanReplication.
- Created WanService and refactored the controller and status logic.
Wan Replication configurations will be stored in Hazelcast ConfigMap. When member containers restart, they will be able to continue replication.
=> [CN-647] Add Wan Replication configuration into generated Hazelcast ConfigMap

controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go
When a Hazelcast resource with restore is applied, It set status to Failed without message If given hot-backup resource is not existing. This PR set Hazelcast resource message on non-existing hotbackup.
**Another scenario**
When creating a Hazelcast cluster with restore enabled and referring to a failed hot-backup resource, Hazelcast resource gets stack in pending state and there is no message about it.
=> [CN-655] set Hazelcast resource message on non-existing hotbackup

.github/workflows/pull-request.yml
Added focused test validation into PR builder. The PR builder immediately fails if one of the tests has an 'F' leftover.
No more focused tests in the codebase.
=> [CN-652]-Add focused tests validator into PR builder

.github/scripts/utils.sh, .github/workflows/publish-release.yaml, Dockerfile
- Added sync_tag function that fetched and attached the latest tag to the published certificate image on Open Shift env
- Changed the tag for the ubi-minimal image to fix the vulnerability issue. Publishing with the current tag will get an index score of C instead of A, and it will cause the impossibility to publish our next image
- No more needs to sync tags manually after publishing
- From now we should always get an index score of A for our subsequent releases
=> [CN-631]-add sync_tags function to fetch latest tag

controllers/hazelcast/wanreplication_controller.go
Reverse incorrect equality check for failed Wan Status
=> Reverse incorrect condition in Wan Replication Controller

controllers/hazelcast/fakes_test.go, internal/hazelcast-client/client.go, internal/phonehome/phonehome.go, main.go
Phone home data will also include the UUIDs of the created Hazelcast clusters.
Cluster UUIDs will be collected in the Phone Home data
=> [CN-661] Add clusterIDs to phone home data

Makefile
Changes:
- When a tool version is updated in the Makefile. The subsequent commands will now use the updated tool version. This behaviour was not present for some of the tools. So, when a tool version was updated the tool version could be the old one.
- Some of the tools were installed into separate folders. Now all the tools are installed in the `TOOLBIN` directory. 
- Tool installation directives do not print anything but the location of the tools binary. So, for example `make operator-sdk` will return the binary location so if you want to use the binaries outside of the Makefile it is possible. An example:
```
$(make controller-gen) --version
```
=> [CN-689] Unify the tool installation mode

.github/workflows/helm-chart-release.yaml
Added a new workflow that allows pushing helm chart directly into https://github.com/hazelcast/charts.git based on changes in helm-chart/ folder in current repo
=> [CN-668] - Sync Hazelcast Operator repo with Hazelcast Charts repo

.github/workflows/pull-request.yml
Fix golangci-lint issue when it throw the error
`
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/apiextensions-apiserver@v0.25.4/pkg/apiserver/schema/cel/values.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/apiextensions-apiserver@v0.25.4/pkg/apiserver/schema/cel/maplist.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/apiextensions-apiserver@v0.25.4/pkg/apiserver/schema/cel/values_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/apiextensions-apiserver@v0.25.4/pkg/apiserver/schema/cel/maplist_test.go: Cannot open: File exists`
- This is because the "Cache Golang dependencies" in PR builder step restores the cache, then the lint action tries to restore the cache as well, and of course, it fails …
=> Remove 'Cache Golang dependencies' step linters job

api/v1alpha1/hazelcast_types.go, api/v1alpha1/hazelcast_validation.go, api/v1alpha1/hazelcast_webhook.go, api/v1alpha1/map_validation.go, api/v1alpha1/map_webhook.go, bundle.yaml, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/samples/_v1alpha1_hazelcast_high_availability.yaml, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/map_controller.go, internal/config/hazelcast.go, internal/phonehome/phonehome.go, test/integration/hazelcast_controller_test.go, test/integration/hazelcast_webhook_test.go
Other changes:
- implemented webhook to validate(prevent) highAvailabilityMode update.
- renamed ValidateNotUpdatableFields to ValidateNotUpdatableMapFields which belongs to Map CR webhook.
- implemented integration tests for feature itself and webhook.
- phone home for highAvailabilityMode param
Introduce highAvailabilityMode is a configuration to create clusters that are resilient to node and zone failures.
=> [CN-606][CN-607] Introduce highAvailabilityMode is configuration to create clusters are resilient to node and zone failures

controllers/hazelcast/hazelcast_resources.go
After members restart they will be able to continue replicating the map entries using Wan Replication
=> Fix wrong variable assignment in WanRep ConfigMap

controllers/hazelcast/hazelcast_resources.go
```
$ k get pod -w
NAME          READY   STATUS    RESTARTS   AGE
hazelcast-0   0/1     Running   0          2s
hazelcast-1   0/1     Running   0          2s
hazelcast-2   0/1     Running   0          2s
hazelcast-0   1/1     Running   0          10s
hazelcast-1   1/1     Running   0          10s
hazelcast-2   1/1     Running   0          10s
```
=> [CN-659] Use podManagementPolicy to improve cluster setup time

.github/workflows/pull-request.yml
Previously we had `bundle.yaml` and we were checking in the pr builder if there is any update from `main` branch on `bundle.yaml`
Now instead of `bundle.yaml` we have `all-crds.yaml`. Without similar check for `all-crds.yaml`, it could lead to broken yaml or missing changes on it.
=> Add if all-crds.yaml is updated check to the pr builder

.github/pr-autolabeler-config.yml, .github/workflows/pull-request-label-update.yaml
Add separate config to update only PR labels in PR builder. Before each merge to the main it updates RN.
=> Add separate config to update only PR labels in PR builder

api/v1alpha1/hazelcast_validation.go, internal/naming/constants.go, test/integration/hazelcast_webhook_test.go
This PR adds a validation to admission web-hook to check if request cluster size is not more than 300.
User won't be able to request a cluster size more than 300 members.
Fixes https://github.com/hazelcast/hazelcast-platform-operator/issues/11
=> [CN-703] Validate if cluster size is not more than 300 in hazelcast cr

Makefile, api/v1alpha1/hazelcast_webhook.go, config/rbac/role.yaml, config/samples/_v1alpha1_hazelcast_persistence.yaml, config/samples/_v1alpha1_hazelcast_persistence_agent.yaml, config/samples/_v1alpha1_hazelcast_persistence_force_start.yaml, config/samples/_v1alpha1_hazelcast_persistence_restore.yaml, controllers/hazelcast/cache_controller.go, controllers/hazelcast/cronhotbackup_controller.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/map_controller.go, controllers/hazelcast/multimap_controller.go, controllers/hazelcast/queue_controller.go, controllers/hazelcast/replicatedmap_controller.go, controllers/hazelcast/topic_controller.go, controllers/hazelcast/wanreplication_controller.go, controllers/managementcenter/managementcenter_controller.go, helm-charts/hazelcast-platform-operator/templates/role.yaml, main.go, test/e2e/hazelcast_persistence_test.go
There are two kinds of roles the operator needs. 
- Roles needed only for the namespace operator runs in
- Roles needed for namespaces operator watches.
This PR separates them visually, so when we generate ClusterRoles in the future we won't mistakenly create ClusterRoles for roles needed only for operator namespace.
=> [CN-660] Separate Watched and Operator Namespace roles 

Makefile
When I run `make sync-manifests` command, it works well and output is as expected. However, when this `make sync-manifests` command is executed from `tilt`, its output is slightly different.
```
→     - securitycontextconstraints
→   verbs:
→     - use
→ ---
→ # Source: hazelcast-platform-operator/templates/crrsterrole.yaml
→ apiVersion: rbac.authorization.k8s.io/v1
→ kind: ClusterRole
→ metadata:
→   name: v1-hazelcast-platform-operator
→   labels:
→     helm.sh/chart: hazelcast-platform-operator-5.6.0
→     app.kubernetes.io/name: hazelcast-platform-operator
→     app.kubernetes.io/instance: v1
```
The name of cluster role file is changed to `crrsterrole.yaml` unexpectedly.
```
Traceback (most recent call last):
/Users/semih/hazelcast/operator/hazelcast-platform-operator/Tiltfile:57:9: …
```
=> Fix make tilt target

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/samples/_v1alpha1_hazelcast_jvm_memory.yaml, controllers/hazelcast/hazelcast_resources.go, controllers/managementcenter/managementcenter_resources.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
Following configuration parameters were added to Hazelcast CR:
1. spec.jvm.memory.initialRAMPercentage (`-XX:InitialRAMPercentage`)
2. spec.jvm.memory.minRAMPercentage (`-XX:MinRAMPercentage`)
3. spec.jvm.memory.maxRAMPercentage (`-XX:MaxRAMPercentage`)
In addition by default we add `-XX:+UseContainerSupport` to `JAVA_OPTS`.
User can now configure  `-XX:{Initial,Max,Min}RAMPercentage` JVM options using Hazelcast CR.
=> [CN-671] Support -XX:{Initial,Max,Min}RAMPercentage Java options

api/v1alpha1/map_validation.go, controllers/hazelcast/map_controller.go
Allow using Off-Heap Memory (HD Memory, Native Memory) in Map CR with spec.inMemoryFormat: NATIVE configuration.
=> [CN-673] Support Native Memory format in Map CR

Tiltfile, controllers/hazelcast/fakes_test.go, controllers/hazelcast/hazelcast_controller.go, internal/hazelcast-client/client.go, internal/hazelcast-client/client_registry.go, internal/hazelcast-client/config.go, internal/hazelcast-client/config_test_unit.go, internal/hazelcast-client/logger.go, main.go, test/integration/suite_test.go
Implementing Hazelcast client custom logger adapter for `logr` library which is used in the operator.
For now, it is only for debug-purpose. So there is no config field to set the level of Hz client logger. The level is set to `logger.InfoLevel` in hard-coded way.
=> [CN-687] Custom Logger support for the go client

test/e2e/helpers_test.go
We renamed backup-agent as sidecar-agent but forgot to fix it in tests.
=> fix sidecar agent naming in tests

.github/workflows/certification-tests-and-release.yaml, Makefile, config/manager/disable_phone_home.yaml, config/manager/enable_developer_mode.yaml, config/manager/kustomization.yaml, config/manager/remove_security_context.yaml, config/samples/_v1alpha1_topic.yaml
Bundle generator failed when `role.yaml` file had two `Role` resources with the same name. Merged the `rules` section of them into one `Role` resource.
=> Merge watched and operator namespace roles for bundle generation 

test/e2e/hazelcast_expose_externally_test.go
`hee-1` and `hee-4` are the same test. Removed `hee-4`.
=> Remove duplicate expose externally ee test

api/v1alpha1/wanreplication_types.go, config/crd/bases/hazelcast.com_wanreplications.yaml, controllers/hazelcast/cronhotbackup_controller.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hazelcast_status.go, controllers/hazelcast/map_controller.go, controllers/hazelcast/wanreplication_controller.go, controllers/hazelcast/wanreplication_status.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/naming/constants.go, test/e2e/config/hazelcast/config.go, test/e2e/custom_resource_test.go, test/e2e/hazelcast_wan_test.go, test/e2e/helpers_test.go, test/e2e/util_test.go
Added support for deletion of wan replicated maps
Added finalizer to maps for which we start Wan replication. So, whenthe map is deleted Wan reconciler has the time to do the clean up. I also added owner reference to the maps along with a map watcher to Wan reconciler manager. This is done to be able to trigger the Wan reconciler when a replicated map is marked to be deleted.
Along with the support, did the following:
- Refactored  GetHazelcastClient input parameters
- Fixed bug causing Hazelcast reconciler  to trigger continuously
- Added resourceName to WanMapStatus, this is done to be able to get the map CR from the Wan status
- Fixed incorrect field assignment in Wan ConfigMap creation
- Reordered functions top down approach
- Fixed hidden errors in Hazelcast reconciler update func
- …
=> [CN-685] Add support for Wan replication control over map deletion

Makefile, api/v1alpha1/hazelcast_validation.go, main.go
`wachedNamespaces` variable in Makefile had missing `s`. Also manager parameter in `setManagerWathedNamespaces` was not a pointer, so changes in the options struct had no effect.
=> Fix watchedNamespaces variable and manager options

Makefile
- Added 2 makefile commands to deploy and cleanup operator using OLM bundle
The run command looks like this:
> `make olm-deploy NS=ns-olm MODE=OwnNamespace`  where NS - is a random namespace name and MODE - is one of the available installation modes AllNamespaces|OwnNamespace| SingleNamespace="ns-olm"
It will create a bundle using an image uploaded to ttl.sh service
To cleanup the deployment you should specify the same namespace.
> `make cleanup-olm NS=ns-olm`
=> Add functions to deploy/cleanup operator using OLM

internal/phonehome/phonehome.go, internal/util/operator_info.go, internal/util/util.go, main.go
Defaulted to watching all namespaces when either `NAMESPACE` or `WATCHED_NAMESPACES` variables are empty.
In the table watched ns type will show up as following:
When either `NAMESPACE` or `WATCHED_NAMESPACES`, operator will watch all namespaces.
=> [CN-713] Add phonehome for watched namespace type

test/e2e/hazelcast_expose_externally_test.go
Fixing expose externally e2e flaky test 
`should create Hazelcast cluster exposed with LoadBalancer services and allow connecting with Hazelcast smart client`
=> Fixing flaky expose externally e2e test

controllers/hazelcast/wanreplication_controller.go, internal/util/random.go
Improved map deletion from Wan status when publisher ID was empty. Also improved logs for easier debugging.
=>  Improve map deletion from Wan status 

go.mod, go.sum, tools/version-diff-tool/main.go
Prints api spec differences between version numbers.
Example 1 - if you provide versions:
`version-diff-tool -base=5.2 -revision=5.3` will print diff to `diff_open-api-bundle-5.2.yaml_open-api-bundle-5.3.yaml.txt`
Example 2 - if you don't provide versions, it will compare the latest 2 versions:
`version-diff-tool` will print diff to `diff_open-api-bundle-5.5.yaml_open-api-bundle-5.6.yaml.txt`
=> [CN-746]: Version Diff Tool

api/v1alpha1/cache_types.go, api/v1alpha1/cache_validation.go, api/v1alpha1/cache_webhook.go, api/v1alpha1/common.go, api/v1alpha1/map_types.go, config/crd/bases/hazelcast.com_caches.yaml, config/crd/bases/hazelcast.com_maps.yaml, config/crd/bases/hazelcast.com_replicatedmaps.yaml, controllers/hazelcast/cache_controller.go, controllers/hazelcast/common.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/map_controller.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/phonehome/phonehome.go, internal/protocol/types/cache_config.go, test/e2e/config/hazelcast/config.go, test/e2e/hazelcast_cache_test.go, test/integration/hazelcast_controller_test.go
Adds native memory support for Cache CR.
If user enabled native memory on related Hazelcast resource, then she/he can enable it for any Cache CR by using following configuration:
```
apiVersion: hazelcast.com/v1alpha1
kind: Cache
metadata:
name: cache-sample
spec:
hazelcastResourceName: hazelcast
inMemoryFormat: NATIVE
```
=> [CN-674]: Native Memory Support for Cache

.github/scripts/utils.sh, .github/workflows/generate-test-report.yaml
Added test report status into PR as a comment only if tests failed.
The table contains links (EE and OS) to Allure reports with the last test run number.
=> [CN-492]-Add test report summary to PR as a comment

test/e2e/management_center_test.go
This PR will fix the MC tests related to the error: 
`0/3 nodes are available: 3 Insufficient memory. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.`
=> Limit MC resources

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, controllers/hazelcast/wanreplication_controller.go, go.mod, go.sum, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/dialer/dialer.go, test/integration/hazelcast_controller_test.go, test/integration/suite_test.go
Add default port 5701 to the wan target endpoints if not declared by user.
If port number is not specified in WanReplication endpoints, the default Hazelcast port '5701' is joined to the endpoints.
=> [CN-773] joining default port to endpoints

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/naming/constants.go
Change default Hazelcast version to 5.2.3-SNAPSHOT instead of latest-snapshot
=> Use Hz version 5.2.3-SNAPSHOT

go.mod, go.sum
https://github.com/hazelcast/hazelcast-go-client/tree/release-v1.4.0
=> [CN-779] Update Hazelcast Go client to 1.4.0

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, config/samples/_v1alpha1_hazelcast_mc_monitoring_config.yaml, controllers/hazelcast/hazelcast_resources.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/config/hazelcast.go, test/integration/hazelcast_controller_test.go
Enables MC Configuration in the following document:
https://docs.hazelcast.com/hazelcast/5.2/maintain-cluster/monitoring#management-center
User can configure Management Center monitoring parameters. Example configuration:
```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
name: hazelcast
spec:
clusterSize: 3
repository: 'docker.io/hazelcast/hazelcast-enterprise'
version: '5.2.1'
licenseKeySecret: hazelcast-license-key
managementCenter:
scriptingEnabled: true
consoleEnabled: true
dataAccessEnabled: true
```
=> [CN-802]: Add MC Config

controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/managementcenter/managementcenter_resources.go, go.mod, test/integration/hazelcast_controller_test.go
When operator upgrade happened and if the new operator version assigned new ports to services or permissions to rbac resources, they were not updated. This PR fixes the issue by making them updatable.
Service ports and rbac permission are now able to be updated when operator version upgrade happens
=> [CN-791] Make service ports and rbac permissions updatable

api/v1alpha1/map_types.go, controllers/hazelcast/wanreplication_controller.go, test/e2e/hazelcast_wan_test.go, test/e2e/helpers_test.go
It triggers the WanReplication CR’s reconciler when a new map is created in given Hazelcast in order to start WanReplication for newly created maps. 
WanReplication feature can be activated even for the Map CRs which are created after their WanReplication CR.
=> [CN-551] Trigger WanReplication with Hazelcast resource when new map is created

.github/workflows/k8s-dist-tests.yaml
Commit messages can have characters that can cause bash to have syntax error since the github context is evaluated before the script is run.
=> Fix decision step commit message error

api/v1alpha1/hazelcast_validation.go, test/integration/hazelcast_controller_test.go
Adding constraint to Hazelcast CR to conform DNS-1035.
Hazelcast CR name has the same constraints as DNS-1035 label.
=> [CN-834] Hazelcast CR name validation

Makefile
Arch should always be `amd64` when deploying the operator in a k8s cluster. It shouldn't be taken from the OS where the build process is running on.
=> Explicitly set 'go build arch' to amd64 in Tilt

internal/config/hazelcast.go
Adding `omitempty` tag to MapStore's `properties` field
=> [CN-900] Fixing Map config persistence bug caused by MapStore

test/integration/cronhotbackup_test.go
Fixes the flakiness I encountered in https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/5442657053/jobs/9898184838#step:5:1542
Before the fix, We were getting the first item in HotBackupList (list of all hotBackup) which might be a leftover from previous test cases. Since we are deleting but not waiting the resources to be deleted at the end of the test case, the leftover resource objects might be kept in the cluster while another test cases are running.
=> Fixing the flakiness in CronHotBackup integration tests

api/v1alpha1/hazelcast_validation.go, test/integration/hazelcast_test.go
We realized that there is a restriction for the `NativeMemory.AllocatorType` field when we enabled `Persistence`.
When `Persistence` is enabled, `NativeMemory.AllocatorType` must be `POOLED`. It cannot be `STANDARD`.
So the necessary validation is added for this case.
=> [CN-859] Add validation for NativeMemory.AllocatorType when persistence is enabled

api/v1alpha1/jetjob_types.go, controllers/hazelcast/hazelcast_controller.go, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hazelcast_resources_test.go, controllers/hazelcast/jetjob_controller.go, test/e2e/hazelcast_jetjob_test.go
Finalizer of Hazelcast CR deletes its dependent JetJob CRs. 
When the JetJob CR is deleted, if its Hazelcast CR has marked to be deleted, (we assume that the deletion operation of JetJob CR is triggered by Hazelcast CR finalizer), then the JetJob finalizer does't cancel the actual job. In this way, the jet jobs in the cluster can be recovered by `losslesRestart` in the backup of HotRestart.
When Hazelcast CR object is getting deleted, its dependent JetJob CR objects are deleted as well without canceling the actual jobs. In case of restoring the cluster from a backup, the jobs were in the cluster can be recovered by `losslesRestart`.
=> [CN-882] Delete JetJob CR when its Hazelcast CR is deleted

test/integration/managementcenter_test.go
Added integration test for the tls configuration validation on MC. Validation is added in [another PR](https://github.com/hazelcast/hazelcast-platform-operator/pull/755).
=> [CN-871] Added integration tests for hz clusters' tls configuration on mc

test/e2e/hazelcast_cache_test.go, test/e2e/hazelcast_map_test.go
Added e2e test for the map and cache configuration validation when native memory is not enabled on HZ. The validation is added in [another PR](https://github.com/hazelcast/hazelcast-platform-operator/pull/759).
=> [CN-860] Added e2e tests for map and cache 

api/v1alpha1/map_types.go, api/v1alpha1/map_validation.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/hazelcast.com_maps.yaml, controllers/hazelcast/map_controller.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, test/integration/map_test.go
The error is caused by the nil pointer of `*NearCacheEviction` in `NearCache` struct.
The Fix basically includes:
- refer to `NearCacheEviction` instead of pointer
- adding defaults to `NearCacheEviction`
=> [CN-901] Fixing error in Map reconciler when nearCache is configured

api/v1alpha1/wanreolication_validation.go, api/v1alpha1/wanreplication_validation.go, api/v1alpha1/wanreplication_webhook.go, controllers/hazelcast/wanreplication_controller.go, test/integration/util_test.go, test/integration/wanreplication_test.go
Added webhook validation for WanReplication update and changed the error messages to be consistent with other validations
=> [CN-902] change WanReplication validation

test/e2e/hazelcast_test.go
Increases the timeout duration to 10 mins.  
As the Hz cluster is created without checking (waiting) status of the Hazelcast CR in the test case, then 30 secs might not be enough timeout duration in the next operation. Increasing the timeout may fix the flakiness.
=> [CN-924] Fix flaky External API errors should be reflected to Hazelcast CR status test

helm-charts/hazelcast-platform-operator/templates/NOTES.txt, helm-charts/hazelcast-platform-operator/templates/_helpers.tpl, helm-charts/hazelcast-platform-operator/templates/deployment.yaml, helm-charts/hazelcast-platform-operator/values.yaml
The `imagePullSecrets` field is depreciated and new field, `image.pullSecrets` is exposed.
Users can still set `imagePullSecrets`. 
In `helpers.tpl`, we first check if  `image.pullSecrets` is set then use that field. If not use `imagePullSecrets`.
=> [CN-935] Depreciate `imagePullSecrets` and add `image.pullSecrets` in values.yaml

controllers/managementcenter/managementcenter_resource_test.go, controllers/managementcenter/managementcenter_resources.go, test/integration/managementcenter_test.go
Management Center config format changes from XML to YAML. Also, unit tests changes has made.
Management Center config is in YAML format
=> [CN-840] Management Center config change xml to yaml

controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hazelcast_resources_test.go, controllers/hazelcast/wanreplication_controller.go, test/integration/wanreplication_test.go
Fix subsequent WanReplication CR overwrite previous batch-publishers
=> [CN-919] Fix WanReplication CR overwrite batch-publishers

.github/workflows/pre-release.yaml
Added step into a pre-release workflow that will get the latest HZ and MC version and update it in the files:
- api/v1alpha1/hazelcast_types.go 
- api/v1alpha1/managementcenter_types.go
- internal/naming/constants.go
- All samples files
If the changes are made, then:
1. run the 'make sync-manifests'
2. Create a branch (e.g. update-hz-and-mc) with these changes and then create a PR against 'main'
3. Create a release branch (e.g. 5.9) based on the branch ('update-hz-and-mc') from Step 2
=> [CN-914] Added auto upgrade HZ and MC version step

api/v1alpha1/common_validation.go, controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_controller_test.go, test/e2e/hazelcast_cache_persistence_test.go, test/e2e/hazelcast_map_persistence_test.go
If Persistence is not enabled on Hazelcast, Hotbackup CR will have failed status and corresponding error message.
=> [CN-845] Add persistence validation for hotbackup

.github/workflows/backup-e2e-gke.yaml, .github/workflows/community-operator-tests.yaml, .github/workflows/docs-release.yaml, .github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-ocp.yaml, .github/workflows/high-availability-e2e-gke.yaml, .github/workflows/istio-e2e-gke.yaml, .github/workflows/k8s-cluster-scope-tests.yml, .github/workflows/k8s-dist-tests.yaml, .github/workflows/multi-version-tests.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/publish-release.yaml, .github/workflows/publish-snapshot.yaml, .github/workflows/pull-request.yml
Removed **uses: actions/cache@v3**  because of **uses: actions/setup-go@v4** has a built-in functionality for caching and restoring go modules and build outputs. It uses [toolkit/cache](https://github.com/actions/toolkit/tree/main/packages/cache) under the hood but requires less configuration settings. The caching is turned on by default.
The action defaults to search for the dependency file - go.sum in the repository root, and uses its hash as a part of the cache key. Use cache-dependency-path input for cases when multiple dependency files are used, or they are located in different subdirectories.
It fixed the errors during execution without losing the efficiency of caching. 
```
Error: /usr/bin/tar: ../../../go/pkg/mod/gocloud.dev@v0.24.0/server/health/sqlhealth/sqlhealth.go: Cannot …
```
=> Removed Cache Golang dependencies

test/e2e/hazelcast_backup_test.go
Insufficient timeout (20 sec) lead the test case to flakiness:
https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/5891942299/job/15980442661#step:12:1820
It increases from 20 sec to 1 min.
=> Fix flakiness by increasing timeout duration on the HotBackup bucket test

api/v1alpha1/hazelcast_types.go, api/v1alpha1/hazelcast_validation.go, test/integration/hazelcast_test.go
- Fixing the baseDir field's path bugs
- Introducing  new tests related to that task
- If the baseDir does not start with `/`  we append `/` into prefix.
=> [cn-843] [cn-842] Using basedir for backup without "/" causes error during HZ cluster creation and empty basedir

.github/workflows/publish-release.yaml
Fix the issue when **operatorhub_release** jobs used property BUNDLE_RELEASE_VERSION from **redhat_certified_operator_release**. Since it's running in parallel the output value for BUNDLE_RELEASE_VERSION could be empty while it's already required in **operatorhub_release** job.
=> Fix property dependency in publish-release.yaml forkflow

controllers/hazelcast/hazelcast_resources.go
The services created for WAN don't have OwnerReference to Hazelcast object.
When you list the services after deleting the Hazelcast CR, you will see the WAN services included in the list.
```
NAME                                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
hz-istanbul                            LoadBalancer   10.109.115.61    127.0.0.1     5710:30440/TCP,5711:32275/TCP,5712:32151/TCP,5713:31068/TCP,5714:31963/TCP   25h
```
WAN Services will be deleted right after their Hazelcast resource is deleted.
=> Set OwnerReference in WAN Services

controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hazelcast_resources_test.go
Config generation is fixed.
Corresponding unit tests are added.
The issue is described in [this slack message](https://hazelcast.slack.com/archives/C01KZ897X7G/p1693541996363869).
The proper config is taken from the following doc page:
https://docs.hazelcast.com/hazelcast/5.3/serialization/compact-serialization#configuration
Nothing change on the kubernetes api. Thus no impact for user.
=> Fix compact serialization config generation

controllers/hazelcast/jetjob_controller.go
Name of a JetJobSnapshot should be taken through `SnapshotName()` function
=> Fix JetJobSnapshot name reference

.github/workflows/pull-request.yml, Makefile
Increased the number of parallel jobs from 5 to 10 and decreased the number of GINKGO_PARALLEL_PROCESSES up to 2 for Kind tests
=> [CN-967]Increased number of parallel jobs

controllers/hazelcast/hazelcast_resources.go, test/integration/hazelcastendpoint_test.go
`h.Spec.ExposeExternally.IsSmart()` > `h.Spec.ExposeExternally.IsEnabled()`
=> Fix discovery type HazelcastEndpoint

internal/util/util.go
It removes the incorrect logs in external address function. This function will possibly be removed soon though.
The deleted statement prints the misleading logs when the WAN in advanced network is enabled.
=> Remove incorrect logs in external address function

.github/workflows/docs-release.yaml
FIxed the issue when documentation release failed:
`Already up to date.
[v/5.9 508b36f] Update docs to 5.9
2 files changed, 10 insertions(+), 9 deletions(-)
To https://github.com/hazelcast/hazelcast-platform-operator-docs
! [rejected]        v/5.9 -> v/5.9 (fetch first)
error: failed to push some refs to 'https://github.com/hazelcast/hazelcast-platform-operator-docs'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.`
=> Update docs-release.yaml workflow

api/v1alpha1/cache_types.go, api/v1alpha1/cronhotbackup_types.go, api/v1alpha1/hazelcastendpoint_types.go, api/v1alpha1/hotbackup_types.go, api/v1alpha1/jetjob_types.go, api/v1alpha1/map_types.go, api/v1alpha1/multimap_types.go, api/v1alpha1/queue_types.go, api/v1alpha1/replicatedmap_types.go, api/v1alpha1/topic_types.go, config/crd/bases/hazelcast.com_caches.yaml, config/crd/bases/hazelcast.com_cronhotbackups.yaml, config/crd/bases/hazelcast.com_hazelcastendpoints.yaml, config/crd/bases/hazelcast.com_hotbackups.yaml, config/crd/bases/hazelcast.com_jetjobs.yaml, config/crd/bases/hazelcast.com_maps.yaml, config/crd/bases/hazelcast.com_multimaps.yaml, config/crd/bases/hazelcast.com_queues.yaml, config/crd/bases/hazelcast.com_replicatedmaps.yaml, config/crd/bases/hazelcast.com_topics.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
`hazelcast-resource` column has been added to the `additionalPrinterColumns`
`HAZELCAST-RESOURCE` column is added in the wide output of CRDs which have reference to Hazelcast CR.
```
$ kubectl get map -o wide
NAME    STATUS    HAZELCAST-RESOURCE   MESSAGE
users   Success   hz-sample
$ kubectl get hotbackup -o wide
NAME                         STATUS    HAZELCAST-RESOURCE   MESSAGE
cron-hot-backup-1697037000   Success   hazelcast
hot-backup                   Success   hazelcast
```
=> [CN-1004] Print HazelcastReference column in the wide output of CRDs referencing to Hazelcast CR

controllers/hazelcast/hazelcast_resources.go, test/integration/hazelcastendpoint_test.go
When the WANConfig under the AdvancedNetwork **is not configured**;
```
Hazelcast Endpoint CRs:
NAME            TYPE        ADDRESS
hazelcast       Discovery   127.0.0.1:5701
hazelcast-0     Member      127.0.0.1:5701
hazelcast-1     Member      127.0.0.1:5701
hazelcast-2     Member      127.0.0.1:5701
hazelcast-wan   WAN         127.0.0.1:5710 // Default WAN port in the discovery service
```
When the WANConfig under the AdvancedNetwork **is configured**;
```
Hazelcast Endpoint CRs:
NAME                   TYPE        ADDRESS
hazelcast              Discovery   127.0.0.1:5701
hazelcast-0            Member      127.0.0.1:5701
hazelcast-1            Member      127.0.0.1:5701
hazelcast-2            Member      127.0.0.1:5701
hazelcast-istanbul-0   WAN         127.0.0.1:5710 …
```
=> [CN-1039] Create Hazelcast Endpoint CR for the default WAN port

api/v1alpha1/hazelcast_validation.go, api/v1alpha1/hazelcast_webhook.go, api/v1alpha1/jetjob_validation.go, api/v1alpha1/jetjobsnapshot_validation.go, api/v1alpha1/managementcenter_webhook.go
Before HZ and MC deletion, we are removing finalizer and updating the CR. Thus, webhook's **ValidateUpdate** function is triggered for them. If there is a broken state for the CR, we were not able to remove finalizer and stuck at the ValidateUpdate function. In order to solve this issue, we add a check to the function. If the CR is marked as deleted(using DeletionTimestamp), we skip the validation.
=> [CN-1049] Skip validations on MC and HZ deletion

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
There is a k8s limitation that port names can be at most 15 character. We are adding 6-7 characters to given WANConfig name field to generate port name. We need to set a length limit to the WanConfig name field.
```
advancedNetwork:
wan:
- name: istanbul (Length limit is introduced. Max length is 8) 
port: 5710
portCount: 5
serviceType: LoadBalancer
```
=> [CN-1071] Set a max length limit to the WanConfig name field

main.go
Previously the operator was trying to watch the resources in the operator's own namespace when **WatchedNsTypeSingle** and  **WatchedNsTypeMulti** but necessary permission was not given to the according service account. Also this scenario was not intended to be supported.
When **watchedNamespaces** is specified, the operator will no longer watch its own namespace by default. If you want it to watch, you need to specify the namespace explicitly with the **watchedNamespaces**.
=> [CN-1070] Remove watching of resources in operator's own namespace when watchedNamespaces is specified

Makefile, test/e2e/hazelcast_expose_externally_test.go, test/e2e/options_test.go
Defines `kind` flag in e2e tests to skip external address checks.
=> [CN-1106] Define kind flag in e2e tests to skip external address checks

.github/workflows/backup-e2e-gke.yaml, .github/workflows/community-operator-tests.yaml, .github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-high-load.yaml, .github/workflows/e2e-ocp.yaml, .github/workflows/generate-test-report.yaml, .github/workflows/high-availability-e2e-gke.yaml, .github/workflows/istio-e2e-gke.yaml, .github/workflows/k8s-cluster-scope-tests.yml, .github/workflows/k8s-dist-tests.yaml, .github/workflows/multi-version-tests.yaml, .github/workflows/nightly-ph-gke.yaml, .github/workflows/nightly-wan-e2e-gke.yaml, .github/workflows/publish-release.yaml, .github/workflows/pull-request.yml, .github/workflows/test-and-release.yaml
Downgrade the 3 actions because of the breaking changes like these. Also @v4 is not compatible with @v3
- Uploading to the same named Artifact multiple times.
- Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.
=> Downgrade the action upload,download and delete actions from @v4 to @v3

controllers/hazelcast/hazelcast_resources.go, test/integration/hazelcast_properties_test.go, test/integration/hazelcast_test.go
This change sets `hazelcast.cluster.version.auto.upgrade.enabled` by default.
As mentioned in the [Hazelcast Rolling Upgrade Document](https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rolling-upgrades#rolling-upgrade-procedure), last step of the upgrade procedure is to trigger a rolling upgrade on the cluster. With this change, Hazelcast Platform Operator triggers it automatically by setting `hazelcast.cluster.version.auto.upgrade.enabled` to `true` by default.
=> [CN-1113]: Add property to enable auto upgrade by default

test/e2e/hazelcast_test.go, test/e2e/helpers_test.go
Check restartCount of Hazelcast containers. It let us detect potential bugs in some specific cases e.g. expose-externally.
=> Check Hazelcast members' container restart count

.github/workflows/e2e-ocp.yaml
We've decided to temporarily skip the NodePort test case in the OCP workflow.
It will be reactivated after fixing the OCP network setup.
see: CN-1126
=> [CN-1106] Skip NodePort test case in OCP workflow

api/v1alpha1/hotbackup_validation.go, controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_controller_test.go
Use the `HotBackup` object as the source object of the error instead of the `Hazelcast` object.
https://github.com/hazelcast/hazelcast-platform-operator/pull/981#discussion_r1475710007
=> Refactor HotBackup persistence validation

api/v1alpha1/managementcenter_types.go, api/v1alpha1/managementcenter_validation.go, config/crd/bases/hazelcast.com_managementcenters.yaml, controllers/managementcenter/managementcenter_resource_test.go, controllers/managementcenter/managementcenter_resources.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, test/integration/hazelcast_config_test.go, test/integration/hazelcast_properties_test.go, test/integration/hazelcast_test.go, test/integration/managementcenter_test.go, test/integration/util_test.go
Ingress `path` section in external connectivity is exposed in MC.
The ingress path for external connectivity in the Management Center CR is configurable.
=> [CN-1082] Expose path fields for MC Ingress configuration

api/v1alpha1/hazelcast_types.go, api/v1alpha1/hazelcast_validation.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, controllers/hazelcast/hazelcast_resources.go, controllers/hazelcast/hot_backup_controller.go, controllers/hazelcast/hot_backup_controller_test.go, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, internal/naming/constants.go, test/e2e/backup_restore_test.go, test/e2e/config/hazelcast/config.go, test/integration/hazelcast_test.go, test/integration/hotbackup_test.go
Hazelcast CR's `persistence.baseDir` field is not configurable anymore, it will managed by the operator.
Users don't need to configure Hazelcast CR's `persistence.baseDir` field that it will be managed by the operator internally.
=> [CN-1100]: remove base-dir

.github/workflows/e2e-platform-misc.yaml, .github/workflows/pull-request.yml, test/e2e/backup_restore_test.go, test/e2e/cache_test.go, test/e2e/e2e_suite_test.go, test/e2e/hazelcast_test.go, test/e2e/jetjob_test.go, test/e2e/jetjobsnapshot_test.go, test/e2e/management_center_test.go, test/e2e/map_test.go, test/e2e/multi_ns_test.go, test/e2e/paltform_wan_test.go, test/e2e/platform_persistence_test.go, test/e2e/platform_resilience_test.go, test/e2e/platform_rolling_upgrade_test.go, test/e2e/platform_rollout_restart_test.go, test/e2e/platform_soak_test.go, test/e2e/wan_sync_test.go, test/e2e/wan_test.go
Add `&& EE` label condition by overriding the label-selector before starting the suite when the `--ee` flag is passed.
https://onsi.github.io/ginkgo/#overriding-ginkgos-command-line-configuration-in-the-suite
This is how we set license (`EE`, `OS`) labelFilter regarding the `--ee` flag.
```go
func SetLicenseLabelFilters(suiteConfig *ginkgoTypes.SuiteConfig) {
if ee {
suiteConfig.LabelFilter += fmt.Sprintf(" && %s", tagNames[EE])
} else {
suiteConfig.LabelFilter += fmt.Sprintf(" && %s", tagNames[OS])
}
}
```
=> Remove explicit skip checks

controllers/hazelcast/hazelcast_resources.go, test/integration/hazelcast_properties_test.go
Makes `hazelcast.persistence.auto.cluster.state.strategy` configurable.
Users will be able to configure `hazelcast.persistence.auto.cluster.state.strategy`.
=> [CN-1135]: make hazelcast.persistence.auto.cluster.state.strategy configurable

api/v1alpha1/hazelcast_validation.go
The `current` and `last` should have been compared by `DeepEqual`, since the `BucketConfiguration` is a pointer type in `RestoreConfiguration`.
```go
type RestoreConfiguration struct {
// Bucket Configuration from which the backup will be downloaded.
// +optional
BucketConfiguration *BucketConfiguration `json:"bucketConfig,omitempty"`
// Name of the HotBackup resource from which backup will be fetched.
// +optional
HotBackupResourceName string `json:"hotBackupResourceName,omitempty"`
}
```
=> Fix restore comparison in validation

controllers/hazelcast/hazelcast_resources.go
The Hazelcast reconciler keeps printing the repetitive logs related to the properties, although I don't set any field for properties.
```
1.708432147727583e+09	DEBUG	controllers.Hazelcast	Property ignored	{"hazelcast": "default/hz-external", "property": "hazelcast.cluster.version.auto.upgrade.enabled"}
1.7084321477277038e+09	DEBUG	controllers.Hazelcast	Property ignored	{"hazelcast": "default/hz-external", "property": "hazelcast.persistence.auto.cluster.state"}
1.7084321477277675e+09	DEBUG	controllers.Hazelcast	Property ignored	{"hazelcast": "default/hz-external", "property": "hazelcast.persistence.auto.cluster.state.strategy"}
1.7084321478103867e+09	DEBUG	controllers.Hazelcast	Property ignored	{"hazelcast": "default/hz-external", "property": …
```
=> Refactoring on property logs

test/e2e/e2e_suite_test.go
`focus` requires no `LabelFilter`
Therefore, we shouldn't even set license labels to be able trigger focus.
=> Fix E2E test focus

.github/scripts/utils.sh, Makefile
After this PR there is no possibility to downgrade ginkgo version [[CN-962] Upgrade operator-sdk version to 1.28.1 by semihbkgr · Pull Request #1038 · hazelcast/hazelcast-platform-operator](https://github.com/hazelcast/hazelcast-platform-operator/pull/1038/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R15)
So this PR fix the test report.
[CN-962]: https://hazelcast.atlassian.net/browse/CN-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CN-1161]Make the test report compatible with latest ginkgo version

api/v1alpha1/map_validation.go, internal/controller/hazelcast/map_resources_test.go, internal/naming/constants.go, test/e2e/config/hazelcast/config.go, test/e2e/helpers_test.go, test/e2e/platform_tiered_storage_test.go, test/maploader/maploader.go
Added 3 tests:
* Ensure that the cluster throws DeviceOutOfCapacityException when the data load exceeds the sum of memory-tier capacity and device capacity.
* Ensure that scaling down and up back should successfully formed the cluster and no data loss.
* Ensure that member join the cluster after ungraceful member shutdown.
=> [CN-1118] Add Platform Tiered-Storage tests

.github/workflows/test-and-release.yaml
5.11.0 doesn't support baseDir so it should be removed
=> [CN-1168] Update test-and-release.yaml

Makefile
In the previous command we were using `helm template` which is not an actual helm installation. So following annotations and labels were not appended. 
```
meta.helm.sh/release-name: operator-crds
meta.helm.sh/release-namespace: default
app.kubernetes.io/managed-by: Helm
``` 
When we try to use `helm install` or `helm upgrade` command for the crds in our ocp cluster, we were getting the following error 
```
Error: INSTALLATION FAILED: Unable to continue with install: CustomResourceDefinition "caches.hazelcast.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to …
```
=> Update make install-crds and uninstall-crds commands

.github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-kind.yaml
To avoid the wrong order in report, the report creation was disabled in WF if it’s not triggered by Push event into main
=> [CN-1248]Remove reports creation for non-distribution tests

internal/controller/hazelcast/hazelcast_resources.go
Change Hazelcast members' logging pattern to include thread name as well.
Users will be able to see thread name in the logs of Hazelcast members.
=> [CN-1255]: add threadName to logging pattern

helm-charts/hazelcast-platform-operator/templates/_helpers.tpl
Here is the error seen in the operator log:
`E0425 15:01:06.189842      34 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.Node: unknown (get nodes)`
=> [CN-1259] Fix Failed to watch *v1.Node: unknown (get nodes)

test/e2e/backup_restore_test.go
In AKS cluster `PartialStart action and MostRecent policy` test is flaky. After my investigation, it seems that the issue is one of the member try to join the cluster after `validation-timeout` is expired.
**The failed member log where we can see reason of failure.**  
```
2024-05-02 19:14:24.100	
{"time":"2024-05-02T16:14:24,099", "level": "ERROR", "threadName": "hz.amazing_ardinghelli.priority-generic-operation.thread-0", "logger": "com.hazelcast.security", "msg": "[10.2
44.0.101]:5702 [dev] [5.4.0] Node could not join cluster. Before join check failed node is going to shutdown now! "}
2024-05-02 19:14:24.100	
{"time":"2024-05-02T16:14:24,100", "level": "ERROR", "threadName": "hz.amazing_ardinghelli.priority-generic-operation.thread-0", "logger": "com.hazelcast.security", "msg": …
```
=> [CN-1275] Increase DataRecoveryTimeout(ValidationTimeout) in the PartialStart test

.github/scripts/utils.sh, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-platfrom-soak.yaml
Use `eksctl` to delete EKS clusters after the AWS tests.
If it fails, we can continue using the current method defined in #546
=> Delete EKS test clusters using 'eksctl'

.github/workflows/publish-release.yaml
* Fixed issue with DockerHub API to get the latest tag before the release
* Fixed DockerHub API to remove the published images correctly
* Added command to update ci.yaml with `merge: false` property in certified-operators repo. Also added option to pause merge in community-operators-prod and community-operators
* Added `validate-release` job that will wait manual approval for the success release. In case of rejection - revert job will be triggered.
* Made all revert steps async
=> [CN-1291] Update publish-release workflow

test/e2e/expose_externally_test.go, test/e2e/helpers_test.go
It was flaky only in the AKS cluster because the provisioned public IP addresses might not be accessible for a short time after being assigned to your resources (e.g., LoadBalancer Service) in Azure.
The test case fails at the moment it checks whether the client has connected to all the members in the cluster. The client cannot connect to all members because the public IP addresses are not reachable at the time the client initiates.
Additionally, the existing client cannot reconnect to the member after the IP addresses became accessible.
The flakiness is fixed by creating new client before checking if the client has connected to all the members.
=> [CN-1274] Fix expose externally load balancer flaky e2e test

.github/workflows/publish-release.yaml, .github/workflows/test-and-release.yaml
- Fix minor issue in getting helm chart version. Recent API call return 5.13.0-snapshot as stable version instead of 5.12.0
- Fix warning "Input 'token' has been deprecated with message: Token is no longer required."
- Remove double quotes from if condition
=> Fix publish release workflow

internal/controller/hazelcast/fakes_test.go, internal/controller/hazelcast/hazelcast_resources_test.go, internal/controller/hazelcast/map_controller.go, internal/controller/hazelcast/map_resources_test.go
When MapConfig creation fails to apply, the Map status will be set to Failed
=> Fix map status when MapConfig creation failed [CN-1226]

.github/workflows/e2e-aks.yaml, .github/workflows/e2e-eks.yaml, .github/workflows/e2e-gke.yaml, .github/workflows/e2e-istio.yaml, .github/workflows/e2e-platfrom-soak.yaml
The distribution workflow calls `run-aks` , `run-eks` and `run-gke` jobs referencing to yaml files. All these jobs create cluster with the same name. This makes it harder to filter logs by cluster in `Grafana` board. We need to create clusters with different names to be able to filter the distribution test logs.
=> [CN-1289] Set different cluster names for each platform in distribution tests

internal/controller/hazelcast/hazelcast_resources.go
Updated existing Hazelcast `5.x` documentation links to use `latest` instead
=> Replace versioned Hazelcast docs with `latest`

.github/workflows/e2e-eks.yaml
Fix the "Error from server (AlreadyExists): namespaces "test-operator-os" already exists" since "eksctl create iamserviceaccount --namespace test-operator-os" command creates namespace if it doesn't exist.
https://eksctl.io/usage/iamserviceaccounts/#:~:text=If%20the%20namespace%20doesn%27t%20exist%20already%2C%20it%20will%20be%20created.
=> Removed redundant NS creation command

internal/controller/hazelcast/fakes_test.go, internal/controller/hazelcast/hot_backup_controller.go, internal/controller/hazelcast/hot_backup_controller_test.go, internal/controller/hazelcast/jetjob_controller.go, internal/controller/hazelcast/usercodenamespace_controller.go, internal/controller/hazelcast/usercodenamespace_controller_test.go, internal/controller/hazelcast/usercodenamespace_status.go, internal/controller/hazelcast/wanreplication_controller.go, internal/hazelcast-client/config_test_unit.go, internal/local_backup/local_backup.go, internal/mtls/client_registry.go
Fix the error `failed to get MTLS client` that can occur after the operator restart
=> Fix error with MTLS client registry after operator restart [CN-1254]

api/v1alpha1/hazelcast_types.go, config/crd/bases/hazelcast.com_hazelcasts.yaml, helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml, test/integration/hazelcast_test.go
This PR adds cannot be empty validation to env var name.
Users won't be able to create CR's which has env var name empty in it.
=> [CN-1329]: Add cannot be empty validation for env var name
